### PR TITLE
Combine BGS and BGS(OR) as one special weapon to count as same counter

### LINKED ISSUE #13402: Bandos godsword and Bandos godsword (or) dont combine damage for corp
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

When using the special attack plugin along with party for duoing corp, if one person has a normal BGS and another has the ornament BGS, you will get two different damage counters

**To Reproduce**
One person with BGS, another with BGS (or)

**Expected behavior**
Two different damage counters, instead of one

**Screenshots**
BGS damage

### PR DESCRIPTION
**Pull request by mdennis1318**
Closes #13402

### CODE REVIEW

**Comment by Adam-** [comment]
This same issue should also be fixed for the bone dagger I think.

**Comment by mdennis1318** [comment]
I agree, but they are more "different" than bgs vs bgs(or) so it is not as clear cut. I will make the update.

**Comment by Adam-** [comment]
I was under the impression their spec was the same, is it not?

**Comment by mdennis1318** [comment]
It is the same, just the weapon itself is slightly different, where the BGS(or) is purely cosmetic

**Comment by Adam-** [comment]
As long as the specs are the same, they should probably be counted as the same within the plugin.

File: runelite-client/src/test/java/net/runelite/client/plugins/specialcounter/SpecialCounterPluginTest.java [hunk 1]
```diff
@@ -258,6 +258,11 @@ public void testNotification()
 		specialCounterPlugin.onVarbitChanged(new VarbitChanged());
 		specialCounterPlugin.onHitsplatApplied(hitsplat(target, Hitsplat.HitsplatType.DAMAGE_ME));
 
+		// Set up spec weapon as BGS(OR)
+		ItemContainer equipment = mock(ItemContainer.class);
+		when(equipment.getItem(EquipmentInventorySlot.WEAPON.getSlotIdx())).thenReturn(new Item(ItemID.BANDOS_GODSWORD_OR, 1));
+		when(client.getItemContainer(InventoryID.EQUIPMENT)).thenReturn(equipment);
+
```
Comment (Nightfirecat) [inline runelite-client/src/test/java/net/runelite/client/plugins/specialcounter/SpecialCounterPluginTest.java:265]: Instead of adding this to an existing test, another test should be added to verify specs from varied weapon types are (a) identified as special attacks, and (b) stacked instead of tracked separately.
