### PR TITLE
Remove pouch counter from Runecraft plugin

### LINKED ISSUE #5667: Runecrafting pouch essence counter is not working anymore
Based on discussion in Discord, the varbits that held the data for stored essence are either gone or changed.

### PR DESCRIPTION
**Pull request by deathbeam**
As it is no longer possible to accurately determine amount of essence in
runecrafting pouch due to varbits for it being removed, remove the
feature.

Closes #5667

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by distillateking** [comment]
:(

File: runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java [hunk 1]
```diff
@@ -32,17 +32,6 @@
 @ConfigGroup("runecraft")
 public interface RunecraftConfig extends Config
 {
-	@ConfigItem(
-		keyName = "showPouch",
-		name = "Show Pouch count",
-		description = "Configures whether the pouch ess count is displayed",
-		position = 1
```
Comment (MagicfTail) [inline runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java]: Change the position of the other configs

Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java]: I wanted to make the change as small as possible, in case we revert this again in future and implement it in different way
