### PR TITLE
gpu: wait for canvas to get it's native peer before starting OpenGL

### LINKED ISSUE #9681: Error starting GPU plugin after updating to 1.5.31 (Ubuntu)
**Describe the bug**
GPU plugin fails to start when launching RuneLite after the latest release. There is an error log entry in `client.log` (see below). Once the client is launched, enabling the GPU plugin works fine, but the next time the client is launched, the plugin is disabled again. Not sure if this affects other platforms, but I am seeing the issue on Ubuntu 18.04.3 LTS.

**To Reproduce**
1. Launch RuneLite

**Expected behavior**
GPU plugin should successfully initialize on startup.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - RuneLite version: 1.5.31.1
 - Launcher version: 1.6.2

**Additional context**
Here are the contents of `client.log`:

```
2019-08-17 07:26:39 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 273267602.227
2019-08-17 07:26:40 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-08-17 07:26:41 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-08-17 07:26:42 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
com.jogamp.opengl.GLException: GLDrawableImpl.setRealized(true): Surface not ready (lockSurface)
        at jogamp.opengl.GLDrawableImpl.setRealized(GLDrawableImpl.java:184)
        at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$0(GpuPlugin.java:266)
        at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
        at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
        at client.je(client.java:15125)
        at client.ag(client.java)
        at bz.fu(bz.java:390)
        at bz.run(bz.java:344)
        at java.lang.Thread.run(Thread.java:748)
2019-08-17 07:26:43 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 7985ms. Uptime: 11154ms
2019-08-17 07:26:44 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,589,286,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@1db80409,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
```

And `launcher.log` (though doesn't look like there's anything relevant here):

```
2019-08-17 07:26:33 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF
2019-08-17 07:26:34 [main] WARN  net.runelite.launcher.PackrConfig - error updating packr vm args!
java.io.FileNotFoundException: /tmp/.mount_runelikM9xJf/config.json (Read-only file system)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at net.runelite.launcher.PackrConfig.updateLauncherArgs(PackrConfig.java:75)
        at net.runelite.launcher.Launcher.main(Launcher.java:178)
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.5.31.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.3.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.3.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-1.3.9.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of error_prone_annotations-2.0.18.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of j2objc-annotations-1.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of animal-sniffer-annotations-1.14.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-amd64.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-i586.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-amd64.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-i586.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-amd64.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-i586.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-amd64.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-i586.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jbsdiff-1.0.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-compress-1.5.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-4.5.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-4.5.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.5.31.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.5.31.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.5.31.1.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.7.0.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.12.0.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-csv-1.4.jar
2019-08-17 07:26:35 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.1.jar
```

As a side note, I noticed the fan on my PC running much louder after the recent update. I don't have a benchmark comparison since this was never an issue previously, but after the update I checked my GPU temps and they're hovering around the max that is recommended (85°C). This happens even when I'm just smithing bars in Varrock - not an especially graphics-intensive activity, I would imagine. Turning the GPU plugin off returns the temps back to normal.

### PR DESCRIPTION
**Pull request by abextm**
Closes #9681

I think this started happening more often because the splash screen delayed the client ui's window getting created, so this race gets hit much more frequently.

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java [hunk 1]
```diff
@@ -243,6 +243,12 @@ protected void startUp()
 				modelBuffer = new GpuIntBuffer();
 
 				canvas = client.getCanvas();
+
+				if (!canvas.isDisplayable())
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/gpu/GpuPlugin.java]: You could just move this check to the very top to prevent allocating all of the buffers each tick
