### PR TITLE
MenuEntrySwapperPlugin: Added Spria

### LINKED ISSUE #13057: NPC contact shift-click doesn't work for Spria
**Describe the bug**
NPC contact shift-click when using the menu entry swapper plugin doesn't swap the option when attempting to contact Spria.

**To Reproduce**
Make sure Spria has already been contacted so it has them as the right-click option.
1. Enable "Menu Entry Swapper" and "NPC Contact" (under UI Swaps).
2. Hold shift when hovering NPC contact to see it doesn't swap for them.

### PR DESCRIPTION
**Pull request by Brandieee**
Resolves #13057

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java [hunk 1]
```diff
@@ -310,10 +310,11 @@ void setupSwaps()
 
 		swap("view offer", "abort offer", () -> shiftModifier() && config.swapGEAbort());
 
-		Arrays.asList(
-			"honest jimmy", "bert the sandman", "advisor ghrim", "dark mage", "lanthus", "turael", "mazchna", "vannaka",
-			"chaeldar", "nieve", "steve", "duradel", "krystilia", "konar", "murphy", "cyrisus", "smoggy", "ginea", "watson",
-			"barbarian guard", "amy", "random"
+		Arrays.asList( //newlines in accordance to UI-layout
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java:313]: ?

Comment (Brandieee) [reply runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java:313]: Linebreaks placed to correspond to the layout of the ingame UI

Comment (Nightfirecat) [reply runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java:313]: Ah, I see. That doesn't need a comment here, though the commit message should probably mention that they've been reformatted here.
