### PR TITLE
Poh plugin: fix mounted glory minimap icon

### LINKED ISSUE #968: Mounted Glory in house does not show on POH overlay
screen shot 2018-03-14 at 9 55 14 pm

### PR DESCRIPTION
**Pull request by sethtroll**
mounted glory is a decoration object, not game object

Fixes #968

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/poh/PohPlugin.java [hunk 1]
```diff
@@ -64,6 +68,9 @@
 	@Getter(AccessLevel.PACKAGE)
 	private final Map<GameObject, Tile> pohObjects = new HashMap<>();
 
+	@Getter(AccessLevel.PACKAGE)
+	private DecorativeObject gloryMount;
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/poh/PohPlugin.java]: Any reason why this isn't a map<deco object, tile>?

Comment (sethtroll) [reply runelite-client/src/main/java/net/runelite/client/plugins/poh/PohPlugin.java]: I did not add a map since the glory mount was the only decorative object we have currently, but I re-added a map for it in case we ever need to add another decorative object.

**Comment by Adam-** [comment]
You may be able to just use a generic map of TileObject instead of the specific object type?

**Comment by sethtroll** [comment]
updated to use tileobject
