### PR TITLE
Fix level 126 next goal to be max XP (200,000,000) instead of -1 xp

### LINKED ISSUE #3658: Xp tracker doesn't track xp gained after hitting virtual level 126 in the skill
You can see in the pic I'm gaining smithing xp but it's not appearing on the tracker. This happened after hitting virtual level 126.

image

### PR DESCRIPTION
**Pull request by LeviSchuck**
This is a fix for endLevelExp being set to -1, which then causes an exception later when creating a snapshot for the GUI. That exception is thrown in `Experience.getLevelForXp` on a `< 0` xp amount.

The fix is to use the max XP value, which also is convenient for those that want to hit the max XP in the game, namely 200,000,000.

image

image

Used `::addxp fishing <big number here>` to test this.

Resolves #3658

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java [hunk 1]
```diff
@@ -220,7 +220,9 @@ boolean update(int currentXp, int goalStartXp, int goalEndXp)
 		if (goalEndXp <= 0 || currentXp > goalEndXp)
 		{
 			int currentLevel = Experience.getLevelForXp(currentXp);
-			endLevelExp = currentLevel + 1 <= Experience.MAX_VIRT_LEVEL ? Experience.getXpForLevel(currentLevel + 1) : -1;
+			endLevelExp = currentLevel + 1 <= Experience.MAX_VIRT_LEVEL
+				? Experience.getXpForLevel(currentLevel + 1)
+				: 200000000;
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java]: `200_000_000`

**Comment by Nightfirecat** [comment]
It would be kind of nice to have a visual indicator that you're working toward `MAX` instead of the start and end level goals being identical.

**Comment by MagicfTail** [comment]
200 would be a nice max ^

File: runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java [hunk 2]
```diff
@@ -248,6 +252,8 @@ XpSnapshotSingle snapshot()
 			.actionsRemainingToGoal(getActionsRemaining())
 			.actionsPerHour(getActionsHr())
 			.timeTillGoal(getTimeTillLevel())
+			.startLevelLabel("Lvl. " + startLevel)
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java]: I would rather propagate startLevelXp and endLevelXp and create labels from UI, I dont think creating of labels should be located here

**Comment by LeviSchuck** [comment]
Made updates @deathbeam
