### PR TITLE
clue scroll: fix hot/cold steps on leagues

### LINKED ISSUE #20073: Hot/cold master clue doesn't work in leagues.
### Type

Crash or hang

### Operating System

None

### OS Version

_No response_

### Bug description

Hot/cold master clue doesn't work in leagues.

### Screenshots or videos

_No response_

### RuneLite version

It does nothing at all

### Logs

_No response_

### PR DESCRIPTION
**Pull request by christoabrown**
fixes #20073

Fixes the clue scroll plugin to work with hot/cold steps in leagues

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java [hunk 1]
```diff
@@ -77,6 +89,11 @@ public class HotColdClue extends ClueScroll implements LocationClueScroll, Locat
 	private WorldPoint location;
 
 	public static HotColdClue forText(String text)
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java]: it looks like this is only left in for the test? the test should just call `forText(String,int)` and then delete this

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java [hunk 2]
```diff
@@ -77,6 +89,11 @@ public class HotColdClue extends ClueScroll implements LocationClueScroll, Locat
...
+	{
+		return forText(text, null);
+	}
+
+	public static HotColdClue forText(String text, Integer clueItemId)
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java]:
```suggestion
	public static HotColdClue forText(String text, int clueItemId)
```

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java [hunk 3]
```diff
@@ -88,6 +105,25 @@ else if (MASTER_CLUE.text.equalsIgnoreCase(text))
...
+				}
+
+				if (clueItemId == ItemID.TRAIL_CLUE_MASTER)
+				{
+					LEAGUE_TUTOR_MASTER_CLUE.reset();
+					return LEAGUE_TUTOR_MASTER_CLUE;
+				}
+			}
+
+			return null;
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java]:
```suggestion

```

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java (hunk 1 above)
Comment (christoabrown) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java]: removed with cec814d

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java (hunk 2 above)
Comment (christoabrown) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java]: done in 21cb9cd

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java (hunk 3 above)
Comment (christoabrown) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java]: done in 21cb9cd

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java [hunk 4]
```diff
@@ -66,6 +67,17 @@ public class HotColdClue extends ClueScroll implements LocationClueScroll, Locat
 		"Speak to Jorral to receive a strange device.",
 		new WorldPoint(2436, 3347, 0),
 		false);
+	private static final String LEAGUE_TUTOR_CLUE_TEXT = "Buried beneath the ground, who knows where it's found. The League Tutor may have a strange device lying around.";
+	private static final HotColdClue LEAGUE_TUTOR_BEGINNER_CLUE = new HotColdClue(LEAGUE_TUTOR_CLUE_TEXT,
+		"Leagues Tutor",
+		"Speak to Leagues Tutor to receive a strange device.",
+		new WorldPoint(1500, 5596, 0),
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java:74]: ~~these coordinates look made up, they should be somewhere near Varlamore..? right?~~

edit: seems the mejrs map isn't updated yet and it just shows a blank square here https://cdn.discordapp.com/attachments/419891709883973642/1495491886385729616/image.png?ex=69e670da&is=69e51f5a&hm=c0f4afc49cb6e3da5078b8ca448c82c2c379e92c8a19a97ead2d9cd34382c9b2&

Comment (christoabrown) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/HotColdClue.java:74]: ah yeah it is the yama's lair with the league tutor npc 
image
