### PR TITLE
Fix 2005 gameframe

### LINKED ISSUE #3007: Interface Styles wrong offset of inventory interfaces
Looks like it needs like umm 20 pixels offset from left. Also, the spell book icon does not match.

screenshot 2018-05-20 10 59 47

### PR DESCRIPTION
**Pull request by raqes**
## Usage
This will align the container of the different tabs to fit better with the 2005 gameframe. It will change the scrollbar to match. Lastly it will add some subtle icons for the different spellbooks.

Credits to @Kamielvf. 

## Related
Fix #3007

### CODE REVIEW

**Comment by Kamielvf** [comment]
Reference to how it looks currently:
image

File: runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java [hunk 1]
```diff
@@ -244,10 +244,18 @@ private void restoreWidgetDimensions()
 
 			if (widget != null)
 			{
-				widget.setRelativeX(widget.getOriginalX());
-				widget.setRelativeY(widget.getOriginalY());
-				widget.setHeight(widget.getOriginalHeight());
-				widget.setWidth(widget.getOriginalWidth());
+				if (widget == client.getWidget(WidgetInfo.FIXED_VIEWPORT_SUB_TAB_CONTAINER))
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java]: what is this for?

Comment (raqes) [reply runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java]: There is no originalHeight and orginalWidth so if I don't exclude it, it will change the width and height to 0.

Comment (raqes) [reply runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/InterfaceStylesPlugin.java]: Could replace it with:
if (widgetOffset.getHeight() == null && widgetOffset.getHeight() == null)

**Comment by raqes** [comment]
Also fixed the 2010 logout button overlay.

File: runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/WidgetOffset.java [hunk 2]
```diff
@@ -34,48 +34,60 @@
...
+	FIXED_2005_MUSIC_HIGHLIGHT(Skin.AROUND_2005, WidgetInfo.FIXED_VIEWPORT_MUSIC_TAB, 206, null, 30, null, true),
+	FIXED_2005_MUSIC_ICON(Skin.AROUND_2005, WidgetInfo.FIXED_VIEWPORT_MUSIC_ICON, 202, 5, null, null, true);
 
 	private Skin skin;
 	private WidgetInfo widgetInfo;
 	private Integer offsetX;
 	private Integer offsetY;
 	private Integer width;
 	private Integer height;
+	private boolean originalWidthAndHeight;
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/WidgetOffset.java]: This would be better if this just defaulted to true

Comment (raqes) [reply runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/WidgetOffset.java]: Done

File: runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/WidgetOffset.java [hunk 3]
```diff
@@ -78,4 +87,28 @@
 	private Integer offsetY;
 	private Integer width;
 	private Integer height;
-}
\ No newline at end of file
+	private boolean originalWidthAndHeight;
+
+	WidgetOffset(Skin skin, WidgetInfo widgetInfo, Integer offsetX, Integer offsetY, Integer width, Integer height)
+	{
+		this.skin = skin;
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/interfacestyles/WidgetOffset.java]: Use constructor chaining instead of duplicating code.
