### PR TITLE
Replace Guava EventBus with our custom one

### LINKED ISSUE #6563: Remember Tag Tab ArrayOutOfBounds exception
When opening the bank to a remembered Tag Tab hundreds of ArrayIndexOutOfBoundsExceptions are thrown.

```
2018-11-18 11:51:56 [Thread-5] WARN  net.runelite.client.RuneLiteModule - uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: null
2018-11-18 11:51:56 [Thread-5] WARN  net.runelite.client.RuneLiteModule - uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.runelite.client.plugins.banktags.BankTagsPlugin.onScriptCallbackEvent(BankTagsPlugin.java:184)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.runelite.client.callback.Hooks.post(Hooks.java:128)
	at gr.au(gr.java:833)
	at o.jl(o.java:11251)
	at client.gz(client.java:5724)
	at client.fk(client.java:2780)
	at client.ad(client.java:1216)
	at ah.ac(ah.java:338)
	at ah.run(ah.java:317)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by deathbeam**
- Add EventBus to replace Guava one
- Replace usages of Guava EventBus with custom one

Depends on #6275 
Fixes #6563 

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

TODO:
- [x] Make registration lazy (probably, from benchmarks I didnt saw any noticeable difference) - decided to not do it not worth the complexity, and there is almost no difference in startup time
- [x] Add support for child events (decided we do not need them)

### CODE REVIEW

File: runelite-api/src/main/java/net/runelite/api/events/EventBus.java [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+			for (final Method method : clazz.getDeclaredMethods())
+			{
+				final Subscribe sub = method.getAnnotation(Subscribe.class);
+
+				if (sub == null)
+				{
+					continue;
+				}
+
+				assert method.getReturnType() == Void.TYPE : "@Subscribed methods cannot return a value";
```
Comment (Adam-) [inline runelite-api/src/main/java/net/runelite/api/events/EventBus.java]: It might be better to use `IllegalArgumentException`

File: runelite-api/pom.xml [hunk 2]
```diff
@@ -50,6 +50,11 @@
 			<artifactId>jsr305</artifactId>
 			<version>1.3.9</version>
 		</dependency>
+		<dependency>
+			<groupId>com.google.guava</groupId>
+			<artifactId>guava</artifactId>
+			<scope>provided</scope>
```
Comment (Adam-) [inline runelite-api/pom.xml]: This probably shouldn't be provided.

File: runelite-api/pom.xml [hunk 3]
```diff
@@ -50,6 +50,11 @@
 			<artifactId>jsr305</artifactId>
 			<version>1.3.9</version>
```
Comment (Adam-) [inline runelite-api/pom.xml]: This is a dependency of guava and also dependency-managed by guava-parent.

File: runelite-api/src/main/java/net/runelite/api/events/EventBus.java [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+	{
+		for (final Subscriber subscriber : subscribers.get(event.getClass()))
+		{
+			try
+			{
+				subscriber.invoke(event);
+			}
+			catch (Exception e)
+			{
+				log.warn("Uncaught exception in event subscriber", e);
```
Comment (Adam-) [inline runelite-api/src/main/java/net/runelite/api/events/EventBus.java]: I kind of liked the exception handler thing guava has for the eventbus ctor, can you just mimic that?

Comment (deathbeam) [reply runelite-api/src/main/java/net/runelite/api/events/EventBus.java]: Do not seems very useful, but sure, updated

**Comment by deathbeam** [comment]
Updated the PR to use LambdaMetaFactory instead of Reflect.Method as it seems faster

File: runelite-api/src/main/java/net/runelite/api/events/EventBus.java (hunk 1 above)
Comment (deathbeam) [reply runelite-api/src/main/java/net/runelite/api/events/EventBus.java]: Replaced with Preconditions.checkArgument

**Comment by deathbeam** [comment]
Updated the PR with privateLookupIn call for Java 9+ (in case they would ever rename the allowedModes field that is accessed via reflection)

**Comment by Adam-** [comment]
This fixes #6563

**Comment by Adam-** [comment]
Commits 75f488d7ae45d19772e4db23e4ad88412311f6ae a290e0bb9357cbc258fe8ce6f0322c5b7f285b5c and 85ce347d6db712b4ebb9fc19bac47f4c2ceebae2 should be squahed into 5c3aebc61c6c82653da51388cb0868b4819fa30d

File: runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java [hunk 5]
```diff
@@ -124,15 +126,8 @@ ChatColorConfig provideChatColorConfig(ConfigManager configManager)
...
-	EventBus provideEventBus()
-	{
-		return new EventBus(RuneLiteModule::eventExceptionHandler);
-	}
-
-	private static void eventExceptionHandler(Throwable exception, SubscriberExceptionContext context)
+	private static void eventExceptionHandler(Throwable exception)
 	{
-		log.warn("uncaught exception in event subscriber", exception);
+		log.warn("Uncaught exception in event subscriber", exception);
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/RuneLiteModule.java]: ?

File: runelite-api/src/main/java/net/runelite/api/events/EventBus.java [hunk 6]
```diff
@@ -0,0 +1,248 @@
...
+
+	private final Consumer<Throwable> exceptionHandler;
+	private ImmutableMultimap<Class, Subscriber> subscribers = ImmutableMultimap.of();
+
+	/**
+	 * Instantiates EventBus with default exception handler
+	 */
+	public EventBus()
+	{
+		this((e) -> log.warn("Uncaught exception in event subscriber", e));
```
Comment (Adam-) [inline runelite-api/src/main/java/net/runelite/api/events/EventBus.java]: If this is the default exception handler we don't need the one in the runelite module anymore. I think it was only there because the default guava one ate exceptions?

File: runelite-api/src/main/java/net/runelite/api/events/EventBus.java [hunk 7]
```diff
@@ -0,0 +1,248 @@
...
+		{
+			for (final Method method : clazz.getDeclaredMethods())
+			{
+				final Subscribe sub = method.getAnnotation(Subscribe.class);
+
+				if (sub == null)
+				{
+					continue;
+				}
+				Preconditions.checkArgument(method.getReturnType() == Void.TYPE, "@Subscribed method \"" + method + "\" cannot return a value");
```
Comment (Adam-) [inline runelite-api/src/main/java/net/runelite/api/events/EventBus.java]: \n here

File: runelite-api/src/main/java/net/runelite/api/events/EventBus.java (hunk 6 above)
Comment (deathbeam) [reply runelite-api/src/main/java/net/runelite/api/events/EventBus.java]: Alright removed the runelite module one, and yes
