### PR TITLE
Fairyring plugin: add tags

### LINKED ISSUE #12388: Suggestion: Fairy Ring Travel Log Nicknames (Tags)
**Would it be possible to add a right click fairy ring code in the travel log>set name (tag)?**

I can't really complain too much the way fairy rings work these days is a massive improvement and I love the travel log + being able to add favourites but I always find myself opening my map and looking for the fairy ring icon for certain areas and getting the code from there, I know it shouldn't be hard to memorise them but some of the descriptions have me stumped I wouldn't think this would be hard to add to the client correct me if I'm wrong but I feel this would be very useful and make things a lot easier.

Examples of how I'd find this useful anyway would be the fairy ring code CIR, I use this atm to get to the farming guild, I am not 100% familiar with Kourend so I get confused, another one when I go fishing for karambwan I am looking for Karamja in the codes descriptions without going back and forth tens of times I wouldn't think to go to the gnome glider as after 15 years of playing on and off I am only just discovering new areas, training methods etc due to playing Ironman.

Not sure how much support this would get and I will eventually learn what is what over time but it would just be really nice to have this option in my honest opinion.

**Some ideas on how this could be implemented (or even toggleable options for multiple);**

1. Change the description of the destination completely underneath the code.
2. Keep the original description but have the nickname in brackets.
3. Have the hover option display the tag.
4. Tag can be searched for in the search bar.

Cheers.

### PR DESCRIPTION
**Pull request by JZomDev**
closes #12388 (found after writing this up)

I didn't see until after I created this that #15968 existed, I had searched for "fairy ring" and only saw the one where the PR only edits the description and not adds the ability to add your own tags. Whoops.

Anyways:

image
image

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingConfig.java [hunk 1]
```diff
@@ -34,10 +34,22 @@ public interface FairyRingConfig extends Config
...
 		return true;
 	}
+
+	@ConfigItem(
+		keyName = "enableFairyTags",
+		name = "Enable Tag searching",
+		description = "Enable the ability to add tags to search fairy ring codes by",
+		position = 2
+	)
+	default boolean enableFairyTags()
```
Comment (raiyni) [inline runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingConfig.java:51]: Personally, I think this can be removed in favor it always being enabled. Other people can provide input on this.

**Review by raiyni — CHANGES_REQUESTED** [review]

File: runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java [hunk 2]
```diff
@@ -316,10 +354,13 @@ else if (!Strings.isNullOrEmpty(w.getText()))
 				}
 			}
 
+			String finalFilter = filter;
 			boolean hidden = !(filter.isEmpty()
 				|| Text.removeTags(c.getDescription().getText()).toLowerCase().contains(filter)
 				|| code.toLowerCase().contains(filter)
-				|| tags != null && tags.contains(filter));
+				|| tags != null && tags.contains(filter)
+				|| (enableTagSearching && tags != null && getTags(code).stream().anyMatch(s -> s.contains(finalFilter))
```
[the remark this answers is not in the document]
Comment (JZomDev) [reply runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java]: I had though that a set contains would match on exact tags being met rather than a partial matching, so I am checking the set to see if any of the Strings within the Collection of Strings match partially the way I knew how.

File: runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java [hunk 3]
```diff
@@ -339,6 +398,17 @@ else if (!Strings.isNullOrEmpty(w.getText()))
 			if (!hidden)
 			{
 				y += c.getDescription().getHeight() + ENTRY_PADDING;
+
+				if (c.getFavorite() != null && c.getFavorite().getSpriteId() == SpriteID.FAIRY_RING_REMOVE_FAVOURITE)
+				{
+					separator.setHidden(false);
+					lastFavorite = c;
+				}
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java:406]: We should only show the separator if both favorite and non-favorite entries are shown. As-is, you can find only favorited entries and have a trailing separator afterwards, which doesn't look good.
Screenshot_20240714_110157

I think this is fixed by un-hiding the separator in the "add padding to the first widget after the separator" case

File: runelite-api/src/main/java/net/runelite/api/ScriptID.java [hunk 4]
```diff
@@ -458,4 +458,7 @@ public final class ScriptID
 
 	@ScriptArguments(integer = 2)
 	public static final int MOTHERLODE_HUD_UPDATE = 1634;
+
+	@ScriptArguments(integer = 1)
```
Comment (Nightfirecat) [inline runelite-api/src/main/java/net/runelite/api/ScriptID.java:462]: This isn't the correct number of args

File: runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java [hunk 5]
```diff
@@ -68,6 +75,7 @@
 )
 public class FairyRingPlugin extends Plugin
 {
+	public static final String CONFIG_GROUP_TAGS = "fairyringtags";
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java:78]: Instead of using a completely separate config group for tags, this can use an additional qualifier, eg. `FairyRingConfig.GROUP + ".tags"`, or something of the like. You can reference the bank tags plugin to see how it manages its config.

File: runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java [hunk 6]
```diff
@@ -212,17 +239,17 @@ public void onGameTick(GameTick t)
...
+		if (!fairyRingWidgetOpen && (searchInputBoxOpen || tagInputBoxOpen))
 		{
 			chatboxPanelManager.close();
 		}
 	}
 
-	private void updateFilter(String filter)
+	private void updateFilter(final String filter)
 	{
-		filter = filter.toLowerCase();
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java:225]: It seems like all callsites are passing strings which are manually lowercased. Is there some reason for this change besides being able to make the parameter to be `final`?

File: runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java [hunk 7]
```diff
@@ -364,4 +434,76 @@ else if (!Strings.isNullOrEmpty(w.getText()))
...
+			clientThread.invokeLater(() -> updateFilter(searchInput.getValue().toLowerCase()));
+		}
+	}
+
+	Collection<String> getTags(String fairyRingCode)
+	{
+		return new LinkedHashSet<>(Text.fromCSV(getTagString(fairyRingCode).toLowerCase()));
+	}
+
+	String getTagString(String fairyRingCode)
```
[the remark this answers is not in the document]
Comment (Nightfirecat) [reply runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java:469]: I agree, this method can be inlined into `getTags()`.

File: runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java (hunk 6 above)
Comment (JZomDev) [reply runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java:225]: I think in one of the commits I made made it so that filter had to be final, I think I can roll that back now if you'd like.

File: runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java [hunk 8]
```diff
@@ -68,6 +76,8 @@
 )
 public class FairyRingPlugin extends Plugin
 {
+	public static final String CONFIG_GROUP = "fairyrings";
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java:79]: We usually define this in the config interface, but it's not really too big a deal where it ends up.
