### PR TITLE
Loot tracker: Track updated wilderness loot keys

### LINKED ISSUE #19295: PVP kills not logging loot in Loot Tracker/Logger
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Since the update on August 20, 2025, loot from player kills is no longer being logged in either the Loot Tracker or the Loot Logger.

This issue might be related to a change in the loot key interface that was part of the same update.
Previously, the trackers would log two separate events for a single player kill:

The player's name and the bones dropped on their death.

The items received after opening the loot key.

Currently, neither of these events is being logged, and the loot from player kills does not appear in the tracker at all.
Note: Loot from NPC kills is still being logged correctly.

### Screenshots or videos

_No response_

### RuneLite version

1.11.14
2.5.0

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Sacca-1**
Fixes the support for loot keys which has been broken since Jagex adopted the deadman-style wilderness loot keys in the main game.

- Hooked the loot tracker into the updated Wilderness loot key interface so it scans the five Deadman loot containers, records each tab separately (with a legacy fallback).
- Updated the chest-reset logic to clear only after all key containers (old and new) are empty.

Fixes #19295

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Given that you can have a wilderness loot chest and a theatre of blood chest both available for looting at once, it might be good to split the checks for them into separate fields.

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 1]
```diff
@@ -1102,8 +1219,9 @@ private void countChangedItems(int itemId, Object metadata)
 	public void onItemContainerChanged(ItemContainerChanged event)
 	{
 		// when the wilderness chest empties, clear chest loot flag for the next key
-		if (event.getContainerId() == InventoryID.LOOT_INV_ACCESS
-			&& Arrays.stream(event.getItemContainer().getItems()).noneMatch(i -> i.getId() > -1))
+		if (isWildernessLootChestContainer(event.getContainerId())
+			&& Arrays.stream(event.getItemContainer().getItems()).noneMatch(i -> i.getId() > -1)
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: this is covered by `areWildernessLootKeyContainersEmpty()`

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 2]
```diff
@@ -880,6 +894,109 @@ public void onWidgetLoaded(WidgetLoaded widgetLoaded)
...
+			if (containerHasItems(client.getItemContainer(id)))
+			{
+				return false;
+			}
+		}
+
+		return true;
+	}
+
+	private boolean containerHasItems(@Nullable ItemContainer container)
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: this can be replaced with `count() > 0`

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 3]
```diff
@@ -880,6 +894,109 @@ public void onWidgetLoaded(WidgetLoaded widgetLoaded)
...
+		}
+
+		return Arrays.stream(container.getItems())
+			.filter(item -> item.getId() > -1)
+			.map(item -> new ItemStack(item.getId(), item.getQuantity()))
+			.collect(Collectors.toList());
+	}
+
+	@Nullable
+	private String getWildernessLootKeyValue(int tabIndex)
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: This is completely useless? why is this being passed as metadata?

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 4]
```diff
@@ -880,6 +894,109 @@ public void onWidgetLoaded(WidgetLoaded widgetLoaded)
...
+			{
+				addLoot("Loot Chest", -1, LootRecordType.EVENT, null, legacyItems);
+				return true;
+			}
+		}
+
+		return recordedLoot;
+	}
+
+	private Collection<ItemStack> toItemStacks(@Nullable ItemContainer container)
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: Make the few other places which have this container stream/map/collect code then call this instead.

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 5]
```diff
@@ -880,6 +894,109 @@ public void onWidgetLoaded(WidgetLoaded widgetLoaded)
...
+			}
+
+			String value = getWildernessLootKeyValue(index);
+			addLoot("Loot Chest", -1, LootRecordType.EVENT, Strings.isNullOrEmpty(value) ? null : value, items);
+			recordedLoot = true;
+		}
+
+		if (!recordedLoot)
+		{
+			Collection<ItemStack> legacyItems = toItemStacks(client.getItemContainer(InventoryID.LOOT_INV_ACCESS));
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: Is this old inventory still used?

**Review by Adam- — CHANGES_REQUESTED** [review]

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java (hunk 3 above)
Comment (Sacca-1) [reply runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: This was a remnant of a different approach - now deleted

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java (hunk 5 above)
Comment (Sacca-1) [reply runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: It is not, I left it initially in case of future changes, but that is indeed not needed.

**Comment by Sacca-1** [comment]
I think that should cover the requested changes, please let me know if there's anything else required.

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 6]
```diff
@@ -141,6 +141,14 @@ public class LootTrackerPlugin extends Plugin
 	private static final int THEATRE_OF_BLOOD_REGION = 12867;
 	private static final int THEATRE_OF_BLOOD_LOBBY = 14642;
 	private static final int BA_LOBBY_REGION = 10039;
+	// Wilderness loot key interface reuses the Deadman loot containers, one per tab
+	private static final int[] WILDERNESS_LOOT_KEY_CONTAINERS = {
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: I'm inclined to rename this `PVP_LOOT_KEY_CONTAINERS` since there's theoretically no reason the loot tracker would not also work for tracking Deadman loot the same way.

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 7]
```diff
@@ -880,6 +887,69 @@ public void onWidgetLoaded(WidgetLoaded widgetLoaded)
...
+			return Collections.emptyList();
+		}
+
+		return Arrays.stream(container.getItems())
+			.filter(item -> item.getId() > -1)
+			.map(item -> new ItemStack(item.getId(), item.getQuantity()))
+			.collect(Collectors.toList());
+	}
+
+	private boolean isWildernessLootChestContainer(int containerId)
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: If you define `private static final List<Integer> WILDERNESS_LOOT_KEY_CONTAINERS = List.of(...)` rather than an array, you can replace this method and its uses with `WILDERNESS_LOOT_KEY_CONTAINERS.contains(containerId)`.

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 8]
```diff
@@ -880,6 +887,56 @@ public void onWidgetLoaded(WidgetLoaded widgetLoaded)
...
+
+		for (int containerId : PVP_LOOT_KEY_CONTAINERS)
+		{
+			final Collection<ItemStack> items = toItemStacks(client.getItemContainer(containerId));
+			if (items.isEmpty())
+			{
+				continue;
+			}
+
+			addLoot("Loot Chest", -1, LootRecordType.EVENT, null, items);
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java:914]: idk if most people would understand "Loot Chest" as a loot source; a quick check with other folks on Discord seems to indicate "Loot key" would be more recognizable (since that's the item turned in to get the loot)
```suggestion
			addLoot("Loot key", -1, LootRecordType.EVENT, null, items);
```

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 9]
```diff
@@ -880,6 +887,56 @@ public void onWidgetLoaded(WidgetLoaded widgetLoaded)
...
+
+		for (int containerId : PVP_LOOT_KEY_CONTAINERS)
+		{
+			final Collection<ItemStack> items = toItemStacks(client.getItemContainer(containerId));
+			if (items.isEmpty())
+			{
+				continue;
+			}
+
+			addLoot("Loot key", -1, LootRecordType.EVENT, null, items);
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: Never mind, "Loot Chest" is how we recorded pvp loot before. We'll keep the name.
```suggestion
			addLoot("Loot Chest", -1, LootRecordType.EVENT, null, items);
```

**Comment by onivalidator** [comment]
Good lord please merge this. We're all suffering.

**Comment by Nightfirecat** [comment]
FYI the `chestLooted` resetting logic you had did not seem to work, I suspect because the loot item containers don't send an event when the interface is closed. I managed to get it working properly by introducing a separate boolean field for pvp chest looting, and resetting it when all loot keys are removed from the inventory.
