### PR TITLE
Check message length before use.

### LINKED ISSUE #8047: ChatCommandsPlugin: "!price" without an item name throws an exception
I was randomly standing around while somebody in public chat wrote `!Price` and it threw an error:

```
2019-02-28 23:36:37 [Thread-3] DEBUG net.runelite.client.RuneLite - Chat message type PUBLIC: !Price
2019-02-28 23:36:37 [Thread-3] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1841)
	at net.runelite.client.plugins.chatcommands.ChatCommandsPlugin.itemPriceLookup(ChatCommandsPlugin.java:578)
```

Moved from https://github.com/runelite/runelite.net/issues/216

### PR DESCRIPTION
**Pull request by pwendelboe**
If we don't check the length of the message before we access it with substring(command.length() + 1) we will get a string index out of range error.
This fixes issue #8047 and #8057.

(Also as a note it's my first pr here so if I did something wrong please let me know thanks!)

Closes #8047

### CODE REVIEW

**Comment by pwendelboe** [comment]
As a side note I would've preferred to do this more dynamically so that it would work with future commands, but I just couldn't figure it out.
~P

**Comment by deathbeam** [comment]
You can just use < everywhere and not add 1. also put newlines around the ifs

**Comment by pwendelboe** [comment]
Ok will do. Thanks!

**Comment by pwendelboe** [comment]
Ok changed. Still need the +1 as otherwise it seems to generate the same error. Since the message of "!price".length() == PRICE_COMMAND_STRING.length() it would fail after changing to just a <. Also added comments to just be explicit about the reason we are testing that.

If there's anything else just let me know.

**Comment by msosa** [comment]
If `x < x + 1` is working than you should be able to just do `x <= x`

**Comment by pwendelboe** [comment]
True. Changed.

File: runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java [hunk 1]
```diff
@@ -629,6 +645,11 @@ private void playerSkillLookup(ChatMessage chatMessage, String message)
 		{
 			return;
 		}
+		
+		if (message.length() <= LEVEL_COMMAND_STRING.length())
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java]: Even though I think this works, this should be moved into the case for message starting with `LEVEL_COMMAND_STRING`

Comment (pwendelboe) [reply runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java]: Oh because it is also called when you do !total. I see, missed that initially. Thanks.
