### PR TITLE
Quest Plugin: Fix null filter state bug

### LINKED ISSUE #11065: NullPointerException in quest plugin
```
2020-03-24 17:52:18 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.questlist.QuestListPlugin.redrawHideButton(QuestListPlugin.java:205)
	at net.runelite.client.plugins.questlist.QuestListPlugin.addQuestButtons(QuestListPlugin.java:152)
	at net.runelite.client.plugins.questlist.QuestListPlugin.onScriptPostFired(QuestListPlugin.java:128)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.callback.Hooks.post(Hooks.java:167)
	at client.ki(client.java:29117)
	at au.t(au.java:154)
	at i.c(e.java:97)
	at client.jk(client.java:3269)
	at client.aw(client.java:1254)
	at bf.ps(bf.java:347)
	at bf.run(bf.java:326)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Repro steps:

1. Turn off Quest List plugin and exit the client
2. Launch client
3. Log in
4. With any tab open, turn on the Quest List plugin
5. Open the quest tab and observe that only the search button is added, the filter orb is not. The error above is logged.

### PR DESCRIPTION
**Pull request by DSerp**
Closes #11065 

The problem was 'currentFilterState' was being set on game state change only when logging in.

Fix was to set it on plugin start up to ALL

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/questlist/QuestListPlugin.java [hunk 1]
```diff
@@ -96,6 +96,7 @@
 	@Override
 	protected void startUp()
 	{
+		currentFilterState = QuestState.ALL;
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/questlist/QuestListPlugin.java]: This should also be reset on shutDown.

Comment (DSerp) [reply runelite-client/src/main/java/net/runelite/client/plugins/questlist/QuestListPlugin.java]: Set it to ALL on shutdown?
