### PR TITLE
Idle Notifier: Notifications for Pottery Crafting

### LINKED ISSUE #8630: Idle Notifier: No Notifications for Pottery Crafting
**Describe the bug**
The Idle Notifier does not notify the user when they are finished interacting with the Potter's Wheel nor when using the Pottery Oven.

Secondly, there is no notification when a player levels up using these crafting methods (as a workaround, a player can be notified by turning on the Screenshot module), even though this feature is present when fishing.

**To Reproduce**
1. Use "soft clay" on **Potter's Wheel** and select an option.
2. Wait to finish.
3. No notification when finished.

--

1. Use "unfired X" (from previous steps) on **Pottery Oven** and select an option (if applicable).
2. Wait to finish.
3. No notification when finished.

**Expected behavior**
Upon transforming all of the items available in your inventory into the finished product, the Idle Notifier should throw a "... is now idle!" notification. Runelite should also notify the player when they level up using these methods.

**Screenshots**
This screenshot shows that Runelite did not output into chat that the player had become idle due to stopping from leveling up while using the pottery crafting benches.
https://i.imgur.com/1AkvZIz.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.20
 - Launcher version: 1.6.0

### PR DESCRIPTION
**Pull request by xDemoN**
Closes #8630 

- Potter's Wheel
- Pottery Oven

### CODE REVIEW

File: runelite-api/src/main/java/net/runelite/api/AnimationID.java [hunk 1]
```diff
@@ -81,6 +81,8 @@
 	public static final int CRAFTING_LEATHER = 1249;
 	public static final int CRAFTING_GLASSBLOWING = 884;
 	public static final int CRAFTING_SPINNING = 894;
+	public static final	int CRAFTING_POTTERS_WHEEL = 883;
```
Comment (beaumitch) [inline runelite-api/src/main/java/net/runelite/api/AnimationID.java]: Accidental spaces
