### PR TITLE
chat-history: fix plugin not clearing history

### LINKED ISSUE #11730: Clear History on Trade/Clan Chat do not work.
**Describe the bug**
Clear History on Trade/Clan chat do not work.

**To Reproduce**
Right click trade and select clear history. 

**Expected behavior**
Clicking 'Clear History' on the tab for Trade/Clan should clear the history.

**Screenshots**
Aqyqf5sBdX

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.17
 - Launcher version: 1.6.0

### PR DESCRIPTION
**Pull request by while-loop**
closes #11730

The cleanup commit in the previous PR accidentally switched `.contains` to `.equals`

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java [hunk 1]
```diff
@@ -254,7 +254,8 @@ public void onMenuOptionClicked(MenuOptionClicked event)
 	{
 		final String menuOption = event.getMenuOption();
 
-		if (CLEAR_HISTORY.equals(menuOption))
+		// The menu option for clear history is "<col=ffff00>Public:</col> Clear history"
+		if (menuOption.contains(CLEAR_HISTORY))
```
Comment (raiyni) [inline runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java:258]: This needs to check better if the right menu option is clicked on the right widgets. As is, any menu options containing `Clear history` will clear the chat history.

Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java:258]: Perhaps `menuOption.endsWith(CLEAR_HISTORY)` to be more explicit?

Comment (while-loop) [reply runelite-client/src/main/java/net/runelite/client/plugins/chathistory/ChatHistoryPlugin.java:258]: I almost did this, but contains seemed "safer" if jagex changes this. I'll use `.endsWith` tho. It's a quick fix anyway.
