### PR TITLE
[FIX] [FEAT] Party plugin and Discord plugin

### LINKED ISSUE #12334: Creation of Discord parties does not work due to Discord changing how it works
Previously, creating a party looked like [this](https://github.com/runelite/runelite/wiki/Party#how-to-create-a-party), with the banner at the top of the window. Now, Discord has changed it to send a channel invite as a DM to the user you asked to join. This fails since channel invites don't work unless a party has been already created.

We're not sure when this change happened, and Discord support still references the banner.

Reported by `Americon` on the Discord.

### PR DESCRIPTION
**Pull request by JoRouss**
I will update the Discord and Plugin readme once this is approved.

Fixes #12334
Closes #7810 which is not a working solution anyways. If you want a working party invite in discord, you can now click Create a party in the Party plugin.

**Definitions**
- Activity: Discord Game Activity previously named Discord Rich Presence

**Fixes**
- Previously, the "Ask to join" button in Activity was permanently displayed in Discord.
    - Now, it only shows up when you are actually in a party, along with the "(x of 15)" where x represents the number of players in your party.

- Previously, anyone clicking the "Ask to join" button would force the player displaying the Activity into a party, displaying a red text as overlay in Runelite, and an unwanted "(1 of 15)" in his activity.
    - Now, the "Ask to join" actually sends a request in-game with the option to invite or not the sender into the party.

- Previously, the party window on Discord side would display your own discord avatar + a default Discord avatar for every other member in your party.
    - Now, the Discord party window actually shows the Discord avatar of every member of your party.

Discord_lovouqENYp

- Previously, the Discord channel party invite would be enabled when you are not in a party, and disappear when in a party and not the owner.
    - Now, it is displayed only when you are in a party. It is enabled even if you are not the party owner, and send a valid party invite.

- Previously, when not in a party, the Discord channel party invite would send an invalid party invite, un-joinable by anyone.
    - Now, the Discord channel party invite sends a valid party invite.

- Previously, party creation workflow: Member1 requests to join Owner. Owner is forced into a party. Owner invites Member1, Member2 and Member3. Members1,2,3 join the party. Members cannot invite anyone else.
    - Now, party creation workflow: Owner creates a party. Owner invites Members1,2,3. Members1,2,3 join the party. Members can invite anyone else.

**New Features**
- Added a party management panel.

- Added a "Create a party" button in the panel.

- Added a "Leave party" button in the panel.

- Previously, members were optionally displayed in an overlay with their Discord name (if using Discord as party creation service), HP and Prayer.
    - Now, members are displayed in the panel, with the addition of their current in-game name, logged-in status and Discord avatar.

- Added the option to include yourself as a member of the party in the panel.

- Previously, you had to display all or no party members in overlay.
    - Now, you can right-click party members in the panel and select "Toggle overlay" to individually add or remove member overlays.

- Added the option to auto-add overlays when someone joins the party.

- ~~Added Runelite PartyService support for join requests and replies.~~ (After review, this design was removed)

- Integrated join requests and replies between Discord plugin and Party plugin.

java_9zpS7nqHge

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/events/PartyJoinRequest.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+ * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+ * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+ */
+package net.runelite.client.events;
+
+import lombok.Value;
+
+@Value
+public class PartyJoinRequest
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/events/PartyJoinRequest.java:30]: What is the purpose of this? It seems like the party service could just use `DiscordJoinRequest` if it needed the join request info. I don't see any reason to try and decouple the party service from discord.

File: runelite-client/src/test/java/net/runelite/client/plugins/discord/DiscordStateTest.java [hunk 2]
```diff
@@ -83,7 +81,8 @@
 	public void before()
 	{
 		Guice.createInjector(BoundFieldModule.of(this)).injectMembers(this);
-		when(partyService.getLocalPartyId()).thenReturn(UUID.nameUUIDFromBytes("test".getBytes(StandardCharsets.UTF_8)));
+		// mockito UnnecessaryStubbingException
```
Comment (Adam-) [inline runelite-client/src/test/java/net/runelite/client/plugins/discord/DiscordStateTest.java:84]: We use git, so you can just remove lines of code instead commenting them out, and still see them in the git history if you need them again.

File: runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java [hunk 3]
```diff
@@ -149,7 +156,6 @@ protected void shutDown() throws Exception
 	{
 		clientToolbar.removeNavigation(discordButton);
 		resetState();
-		partyService.changeParty(null);
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java:152]: The party stuff largely doesn't function without the discord plugin (such as join requests don't work, avatars don't work) and so this was here to remove the player from a party if it was shut off. Why is it removed?

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java [hunk 4]
```diff
@@ -141,17 +156,35 @@ public void configure(Binder binder)
 	@Override
 	protected void startUp() throws Exception
 	{
+		panel = new PartyPanel(this, config, party);
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java:159]: Usually if we want to build a panel that contains a bunch of injectable objects, we instead manually pull it from the injector during startUp(), which correctly will construct it on the swing thread. Eg `injector.getIntance()`. Search some of the other plugins which add panels.

File: runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java (hunk 3 above)
Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java:152]: Because there are other plugins that can be used to join a party, like easy party does it with a partyId directly. Someone can be in a party regardless of discord.
It was necessary before because there was no "leave party" button. I added one.

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java [hunk 5]
```diff
@@ -435,6 +516,9 @@ public void onUserPart(final UserPart event)
 			}
 
 			worldMapManager.remove(removed.getWorldMapPoint());
+
+			panel.updateParty();
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java:520]: Shouldn't this be updating the party after removing the member?

Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java:520]: Doesn't matter, they affect the UI based on the PartyService list.

File: runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java (hunk 3 above)
Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java:152]: But there was leave party button, right click on the in game interface

Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java:152]: Yes that's right. But the interface was also toggleable and did not appear when you were the only party member. The Leave party button is now always there when you are in a party.

Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java:152]: I really dont see how is that related. You are breaking the party by disabling Discord plugin, so why are you not leaving the party as well. If you dont want to interfere with other party plugins that exist I guess? then handle it like that and not completely ignore the issue.

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPanel.java [hunk 6]
```diff
@@ -0,0 +1,213 @@
...
+		startButton.setText(party.isInParty() ? BTN_LEAVE_TEXT : BTN_CREATE_TEXT);
+
+		if (!party.isInParty())
+		{
+			add(noPartyPanel);
+			return;
+		}
+
+		boolean alone = plugin.getPartyDataMap().size() == 1;
+		boolean selfInParty = party.getLocalMember() != null
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPanel.java:148]: How can this be false?

File: runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java [hunk 7]
```diff
@@ -439,4 +471,10 @@ private boolean showArea(final DiscordGameEventType event)
 
 		return false;
 	}
+
+	public static UUID toDiscordPartyId(UUID id)
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java:475]: You are using this method only in DiscordState, move it there

File: runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java [hunk 8]
```diff
@@ -109,11 +108,14 @@ void refresh()
...
+		if (party.isInParty())
 		{
-			// This is only used to identify the invites on Discord's side. Our party ids are the secret.
-			presenceBuilder.partyId(partyId.toString());
-			presenceBuilder.joinSecret(party.getLocalPartyId().toString());
+			// Create a partyID for Discord to consider us part of this party and thus display our avatars on Discord side
+			presenceBuilder.partyId(DiscordPlugin.toDiscordPartyId(party.getPartyId()).toString());
+
+			// It was decided to allow any party members to invite / be requested to join a party
+			//if (party.isPartyOwner())
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java:117]: As adam said in other comment, why are you leaving commented out code aroud. Also move this and the other identical party check in this class to common method

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyConfig.java [hunk 9]
```diff
@@ -74,10 +68,33 @@ default boolean messages()
...
+
+	@ConfigItem(
+		keyName = "autoOverlay",
+		name = "Auto overlay",
+		description = "Automatically add an overlay with player data when a member joins",
+		position = 5
+	)
+	default boolean autoOverlay()
+	{
+		return false;
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/party/PartyConfig.java:87]: Why is this false? You should preserve the original behaviour

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyConfig.java [hunk 10]
```diff
@@ -74,10 +68,33 @@ default boolean messages()
...
+
+	@ConfigItem(
+		keyName = "includeSelf",
+		name = "Include yourself",
+		description = "Shows yourself in the panel as part of the party",
+		position = 6
+	)
+	default boolean includeSelf()
+	{
+		return true;
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/party/PartyConfig.java:98]: See my previous comment

File: runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java (hunk 3 above)
Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java:152]: I don't understand the issue. What do you mean by "handle it like that"?
As you said, I don't want to interfere with other party plugins.
Also, there might be people that enable Discord, join a party and shut discord down. I don't see why Discord has to force someone out of a party when you can decide when to leave by clicking a "Leave party" button. What am I missing here?

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyMemberBox.java [hunk 11]
```diff
@@ -0,0 +1,219 @@
...
+
+		// Update name labels
+		Color playerColor = config.recolorNames() ? memberPartyData.getColor() : Color.WHITE;
+		boolean isLoggedIn = !memberPartyData.getCharacterName().equals("");
+
+		topName.setText(htmlLabel(memberPartyData.getMember().getName(), playerColor));
+		bottomName.setText(htmlLabel(isLoggedIn ? memberPartyData.getCharacterName() : "Logged out", isLoggedIn ? playerColor : Color.GRAY));
+	}
+
+	static String htmlLabel(String value, Color color)
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/party/PartyMemberBox.java:210]: this method is used only here, why is it not private

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyMemberBox.java [hunk 12]
```diff
@@ -0,0 +1,219 @@
...
+	{
+		return String.format(HTML_LABEL_TEMPLATE, ColorUtil.toHexColor(color), value);
+	}
+
+	static String progressBarLabel(int current, int max)
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/party/PartyMemberBox.java:215]: See my previous comment

**Review by deathbeam — CHANGES_REQUESTED** [review]

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyConfig.java (hunk 9 above)
Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/party/PartyConfig.java:87]: Yes I wasn't sure about this. I thought It would duplicate the info by default. I agree the default behavior should be preserved.

File: runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java [hunk 13]
```diff
@@ -290,7 +327,8 @@ public void onResponse(Call call, Response response) throws IOException
 					{
 						image = ImageIO.read(inputStream);
 					}
-					memberById.setAvatar(image);
+
+					partyService.setPartyMemberAvatar(memberById.getMemberId(), image);
```
Comment (JoRouss) [inline runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java:331]: Added an event for when the avatar changes. I'd like a review on that. Thanks!

Changes https://github.com/runelite/runelite/pull/13406/commits/822d88d6bfcb9ab0e34c83eab8c7815d87ba8219

File: runelite-client/src/main/java/net/runelite/client/events/PartyJoinRequest.java (hunk 1 above)
Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/events/PartyJoinRequest.java:30]: I did it this way because they were already decoupled. This way, I can also keep track of which requests were sent through Discord and respond to PartyJoinReply accordingly. I know there can't be requests from any other plugins right now, but I wanted tokeep them decoupled so there can be in the future.

I don't mind coupling them if you want. I'll wait for your decision.

Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/events/PartyJoinRequest.java:30]: This would be the result of coupling DiscordService to PartyPlugin
https://github.com/JoRouss/runelite/commit/585e280db53709659b1877c08e70f93fc39527fb

**Review by abextm — CHANGES_REQUESTED** [review]
There are a lot of useless comments that resemble
```
// set x to 1
x = 1
```
all over; these should be removed. Also some `/* single line */` comments, that if retained, should  be `// single line` comments.

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java [hunk 14]
```diff
@@ -386,31 +462,59 @@ public void onUserJoin(final UserJoin event)
...
+	private void checkStateChanged(boolean forceSend)
 	{
 		final int currentHealth = client.getBoostedSkillLevel(Skill.HITPOINTS);
 		final int currentPrayer = client.getBoostedSkillLevel(Skill.PRAYER);
 		final int realHealth = client.getRealSkillLevel(Skill.HITPOINTS);
 		final int realPrayer = client.getRealSkillLevel(Skill.PRAYER);
 		final PartyMember localMember = party.getLocalMember();
 
+		final Player localPlayer = client.getLocalPlayer();
+		final String characterName = Strings.nullToEmpty(localPlayer != null && client.getGameState().getState() >= GameState.LOADING.getState() ? localPlayer.getName() : null);
```
[the remark this answers is not in the document]
Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java]: The state check is to display "Logged out" when in the login screen. @Adam- removed it. I'll unresolve this, but I don't mind leaving it like this. All it does is keep displaying the latest username when logging out. I felt it was a good idea to have a way to tell a party member was not currently logged in.

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyStatsOverlay.java [hunk 15]
```diff
@@ -62,17 +61,11 @@ private PartyStatsOverlay(final PartyPlugin plugin, final PartyService party, fi
 		this.config = config;
 		panelComponent.setBorder(new Rectangle());
 		panelComponent.setGap(new Point(0, ComponentConstants.STANDARD_BORDER / 2));
-		getMenuEntries().add(new OverlayMenuEntry(MenuAction.RUNELITE_OVERLAY, "Leave", "Party"));
```
[the remark this answers is not in the document]
Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/party/PartyStatsOverlay.java:65]: I felt it was a good idea to move party management stuff in the new party management panel. It doesn't hurt to leave it there though. I'll put it back.

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (Adam-) [reply runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java]: Does the local player exist when logged out? That seems odd.

[the remark this answers is not in the document]
Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java]: Yes, I found it weird too...

File: runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPanel.java [hunk 16]
```diff
@@ -0,0 +1,201 @@
...
+		topPanel.setLayout(new BorderLayout());
+
+		topPanel.add(startButton, BorderLayout.CENTER);
+
+		layoutPanel.add(topPanel);
+		layoutPanel.add(requestBodPanel);
+		layoutPanel.add(memberBoxPanel);
+
+		startButton.setText(party.isInParty() ? BTN_LEAVE_TEXT : BTN_CREATE_TEXT);
+		startButton.setFocusable(false);
```
[the remark this answers is not in the document]
Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPanel.java:92]: To get rid of the focus lines as shown in the picture
java_IJLaz7rYyu

[the remark this answers is not in the document]
Comment (JoRouss) [reply runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPanel.java:92]: duplicate
