### PR TITLE
Fix crystal chest in loot tracker

### LINKED ISSUE #8356: Crystal Chest counts as Brimstone Chest in Loot Tracker
**Describe the bug**
Opening the Crystal Chest in Taverly tracks the loot as the Brimstone Chest in the Loot Tracker plugin

**To Reproduce**
1. Enable the Loot Tracker plugin
2. Acquire a [crystal key](https://oldschool.runescape.wiki/w/Crystal_key)
3. Open the crystal chest in Taverly
4. Check the Loot Tracker plugin to see the loot tracked as a Brimstone Chest

**Expected behavior**
The loot from the chest should either be added to a separate category for Crystal Chest or just be excluded from the Brimstone Chest.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.18
 - Launcher version: Unknown

**Additional context**
Based on the code, it looks like the issue is caused by both events having the same game message of "You find some treasure in the chest!"

### PR DESCRIPTION
**Pull request by AdamBallinger**
Fixes crystal chests counting as brimstone chests in the loot tracker by checking the current region the player is in.
7b8f130b411f09fcb3b7060d7916bd43

Closes #8356

### CODE REVIEW

**Comment by Nightfirecat** [comment]
I feel like we shouldn't just assume that any non-brimstone region is the crystal chest. I don't know that there are many (if any) other chests needing consideration, but logging the loot/location for chest loots in regions outside brimstone/crystal chests might be a better solution.

**Comment by AdamBallinger** [comment]
I've made changes to map each chest to its appropriate region rather than just assuming any other region like you said is the crystal chest. I can't actually think of any other chests that exist in the game that work the same way but adding them if they do should be a simple task, assuming they use the same message "You find some treasure in the chest!".

**Comment by Unmoon** [comment]
Have you checked how [Muddy chests](https://oldschool.runescape.wiki/w/Muddy_chest) and [Sinister chests](https://oldschool.runescape.wiki/w/Sinister_chest) work? There's also the thieving chests listed in the wiki.

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 1]
```diff
@@ -448,11 +457,11 @@ private void processBrimstoneChestLoot(ItemContainer inventoryContainer)
 				.collect(Collectors.toList());
 
 			final LootTrackerItem[] entries = buildEntries(stack(items));
-			SwingUtilities.invokeLater(() -> panel.add(BRIMSTONE_CHEST_EVENT_TYPE, -1, entries));
+			SwingUtilities.invokeLater(() -> panel.add(eventType, -1, entries));
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: This races with nulling of eventType.

**Comment by Adam-** [comment]
IMO we can merge this to fix the crystal/brimstone mixup and then add the other chests in separate PRs.

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 2]
```diff
@@ -456,12 +456,14 @@ private void processChestLoot(ItemContainer inventoryContainer)
 				.map(e -> new ItemStack(e.getElement(), e.getCount(), client.getLocalPlayer().getLocalLocation()))
 				.collect(Collectors.toList());
 
+			final int regionID = client.getLocalPlayer().getWorldLocation().getRegionID();
+			final String chestType = CHEST_EVENT_TYPES.get(regionID);
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java]: this is just `final String chestType = eventType`
