### PR TITLE
Fix tooltip error handling

### LINKED ISSUE #4106: Mouse tooltips keep getting added
As mentioned by the user `Curse of Ares#0534` on discord, after helping his ironman friend with a quest (I assume) by using a key on the ironman to hand it to him, the mouse tooltips kept being added and thus resulted in the following:

preview

### PR DESCRIPTION
**Pull request by Adam-**
Fixes #4106

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java [hunk 1]
```diff
@@ -458,8 +460,23 @@ else if (position == OverlayPosition.TOOLTIP)
 		}
 
 		subGraphics.translate(point.x, point.y);
-		final Dimension dimension = MoreObjects.firstNonNull(overlay.render(subGraphics), new Dimension());
-		subGraphics.dispose();
+
+		Dimension overlayDimension;
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/ui/overlay/OverlayRenderer.java]: This should be final
