### PR TITLE
loot tracker: fix grubby chest false positive loot

### LINKED ISSUE #17049: [Loot Tracker] Other Actions in Grubby Chest area adds to Grubby Chest Count
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Steps to reproduce:

1. "Open Grubby Chest" while holding a Grubby Key or Right click option "Check Grubby Chest"
2. Attempt various actions (eat food, fletch, certain teleports, etc.)

Unexpected effect: The Loot Tracker counter for Grubby Chest increases without opening the chest

Tested:

- Triggering: House tab, Standard Spellbook teleports, Ectophial, Fletching Willow logs, Bury Bones, Eat Mackerel
- Not triggering: Khardest Memoirs teleport out, Xeric's Talisman Teleport out, decanting potions.

Not tested: Not already having a Grubby Chest loot tracked. 

Additional Notes:
Changed to safe mode and tested again, behaviour still occurs

### Screenshots or videos

image

### RuneLite version

1.10.12.2
Rev 216
2.6.3

### Logs

[client.log](https://github.com/runelite/runelite/files/12657894/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12657900/launcher.log)

### PR DESCRIPTION
**Pull request by Macweese**
This PR fixes a possibility of items being mistakenly registered as loot from the Grubby chest, when checking the loot count ("kc") of the chest.

Instead of using a message shared when both looting and checking the chest (as it is currently), a loot-specific message is used to assume tracking. The message has two variations; one for common loot, and one for unique loot. Though they share a similar beginning, I chose to use a pattern (instead of using a string and checking the start of the message) because the shared string felt too generic and I'm not sure if e.g. opening other types of containers (e.g. clue scroll casket¹/random event casket/other) yield a message with similar beginning. This felt the safest.

¹ I recall there is at least 1 clue scroll step in the dungeon, by the red dragons.

The standard loot message:
> You find treasure and supplies within the chest.

The rare loot message:
> You find treasure, supplies, and a weirdly coloured egg sac within the chest.

<details>
  <summary>Debug output from looting the chest</summary>

```log
2025-02-25 15:53:09 CET [Client] DEBUG injected-client - Chat message type SPAM: You unlock the chest with your key.
2025-02-25 15:53:10 CET [Client] DEBUG injected-client - Chat message type GAMEMESSAGE: You have opened the Grubby Chest 19 times.
2025-02-25 15:53:10 CET [Client] DEBUG net.runelite.client.game.LootManager - Item spawn 7056 (1) location LocalPoint(x=6720, y=6848, worldView=-1)
2025-02-25 15:53:10 CET [Client] DEBUG net.runelite.client.game.LootManager - Item spawn 7056 (1) location LocalPoint(x=6720, y=6848, worldView=-1)
2025-02-25 15:53:10 CET [Client] DEBUG net.runelite.client.game.LootManager - Item spawn 7056 (1) location LocalPoint(x=6720, y=6848, worldView=-1)
2025-02-25 15:53:10 CET [Client] DEBUG net.runelite.client.game.LootManager - Item spawn 7056 (1) location LocalPoint(x=6720, y=6848, worldView=-1)
2025-02-25 15:53:10 CET [Client] DEBUG net.runelite.client.game.LootManager - Item spawn 385 (1) location LocalPoint(x=6720, y=6848, worldView=-1)
2025-02-25 15:53:10 CET [Client] DEBUG net.runelite.client.game.LootManager - Item spawn 385 (1) location LocalPoint(x=6720, y=6848, worldView=-1)
2025-02-25 15:53:10 CET [Client] DEBUG net.runelite.client.game.LootManager - Item spawn 385 (1) location LocalPoint(x=6720, y=6848, worldView=-1)
2025-02-25 15:53:10 CET [Client] DEBUG net.runelite.client.game.LootManager - Item spawn 385 (1) location LocalPoint(x=6720, y=6848, worldView=-1)
2025-02-25 15:53:10 CET [Client] DEBUG injected-client - Chat message type MESBOX: You find treasure and supplies within the chest.
2025-02-25 15:53:10 CET [Client] DEBUG n.r.c.p.l.LootTrackerPlugin - Chest loot matched 'You find treasure and supplies within the chest.' region 7323
2025-02-25 15:53:10 CET [Client] DEBUG n.r.c.p.l.LootTrackerPlugin - Inv change: [ItemStack(id=147, quantity=1), ItemStack(id=165, quantity=1), ItemStack(id=989, quantity=1), ItemStack(id=159, quantity=1)] Ground items: [ItemStack(id=7056, quantity=1), ItemStack(id=7056, quantity=1), ItemStack(id=7056, quantity=1), ItemStack(id=7056, quantity=1), ItemStack(id=385, quantity=1), ItemStack(id=385, quantity=1), ItemStack(id=385, quantity=1), ItemStack(id=385, quantity=1)]
2025-02-25 15:53:16 CET [Client] DEBUG injected-client - Chat message type SPAM: You have combined the liquid into four doses.
2025-02-25 15:53:17 CET [Client] DEBUG injected-client - Chat message type SPAM: You have combined the liquid into four doses.
2025-02-25 15:53:19 CET [Client] DEBUG injected-client - Chat message type SPAM: You have combined the liquid into four doses.
```
  
</details>

Fixes #17049

### CODE REVIEW

File: runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java [hunk 1]
```diff
@@ -365,29 +370,45 @@ public void testGrubbyChest()
...
+		lootTrackerPluginSpy.onItemContainerChanged(new ItemContainerChanged(InventoryID.INV, itemContainer));
+
+		// Default loot message
+		ChatMessage chatMessage = new ChatMessage(null, ChatMessageType.MESBOX, "", "You find treasure and supplies within the chest.", "", 0);
 		lootTrackerPluginSpy.onChatMessage(chatMessage);
 
 		when(itemContainer.getItems()).thenReturn(new Item[]{
-			new Item(ItemID.TWISTED_BOW, 1)
+			new Item(ItemID.TWISTED_BOW, 1),
+			new Item(ItemID.HOSDUN_GRUBBY_KEY, 2),
```
Comment (Nightfirecat) [inline runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java:385]: It doesn't affect the integrity of the test case (since items _not_ being removed doesn't impact the loot that's tracked) but we should have the correct number of grubby keys in the inventory at each step.
```suggestion
			new Item(ItemID.HOSDUN_GRUBBY_KEY, 1),
```

File: runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java [hunk 2]
```diff
@@ -365,29 +370,45 @@ public void testGrubbyChest()
...
+		));
+
+		// Unique loot message
+		chatMessage = new ChatMessage(null, ChatMessageType.MESBOX, "", "You find treasure, supplies, and a weirdly coloured egg sac within the chest.", "", 0);
 		lootTrackerPluginSpy.onChatMessage(chatMessage);
 
 		when(itemContainer.getItems()).thenReturn(new Item[]{
 			new Item(ItemID.TWISTED_BOW, 1),
-			new Item(ItemID.SHARK, 42)
+			new Item(ItemID.HOSDUN_GRUBBY_KEY, 1),
```
Comment (Nightfirecat) [inline runelite-client/src/test/java/net/runelite/client/plugins/loottracker/LootTrackerPluginTest.java:400]:
```suggestion
```
