### PR TITLE
Achievement Diary: Add Missing Requirements

### LINKED ISSUE #8210: Achievement diary -some requirements missing
Easy Achievement Diary for Ardougne - "Go out fishing on the Fishing Trawler" - doesn't display the 15 fishing requirement next to it.

Also, for Falador easy diary, you are required to fix a broken strut in the motherlode mine - does this require 30 mining to enter mlm or can you enter at any level?

Fremenik easy diary - "Enter the troll stronghold" - should display requires death plateau and started troll stronghold

Kandarin Easy diary - kill 1 of each elemental in the workshop - requires starting elemental workshop

### PR DESCRIPTION
**Pull request by RyBo**
Fixes #8210 

**Ardougne Easy**  - "Go out fishing on the Fishing Trawler" - requires 15 fishing 
**Fremmy Easy** - "Enter the troll stronghold" - requires death plateau and started troll stronghold
**Kandarin Easy**  - kill 1 of each elemental in the workshop - requires starting elemental workshop
**Kandarin Hard** - Kill a shadow hound in the Shadow Dungeon - requires starting Desert Treasure and 53 thieving
**Falador Hard** - Kill the blue dragon under the Heroes' Guild - requires Heroes' Quest
**Morytania Easy** - Kill a werewolf in its human form using the Wolfbane Dagger - requires Priest in Peril
**Morytania Easy** - Mix a Guthix Balance potion while in Morytania - requires 22 herblore not 36
**Western Diary** - Teleport to Pest Control using the Minigame teleport - requires 40 combat
**Western Diary** - Kill an Elf with a Crystal bow - requires 56 Agility not 50
~~**Western Diary** - Claim a Chompy bird hat from Rantz after registering at least X Kills - requires 5 fletching and 30 ranged.~~

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java [hunk 1]
```diff
@@ -96,6 +96,9 @@ public KandarinDiaryRequirement()
 			new SkillRequirement(Skill.MAGIC, 56));
 		add("Burn some Maple logs with a bow in Seers' Village.",
 			new SkillRequirement(Skill.FIREMAKING, 65));
+		add("Kill a Shadow Hound in the Shadow dungeon.",
+			new SkillRequirement(Skill.THIEVING, 53),
```
Comment (Kamielvf) [inline runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java]: I don't think quest reqs should be shown in the diary reqs like this.

File: runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java [hunk 2]
```diff
@@ -72,7 +76,9 @@ public WesternDiaryRequirement()
 			new QuestRequirement(Quest.ONE_SMALL_FAVOUR),
 			new QuestRequirement(Quest.THE_GRAND_TREE));
 		add("Claim a Chompy bird hat from Rantz after registering at least 125 kills.",
-			new QuestRequirement(Quest.BIG_CHOMPY_BIRD_HUNTING));
+			new QuestRequirement(Quest.BIG_CHOMPY_BIRD_HUNTING),
+			new SkillRequirement(Skill.FLETCHING, 5),
```
Comment (Kamielvf) [inline runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java]: Same for these, they are already part of the quest requirement.

File: runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java (hunk 1 above)
Comment (Nightfirecat) [reply runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java]: It makes sense in this case, since the quest only needs to be partially completed, and this skill is a part of the partial completion step of the quest.

Comment (Kamielvf) [reply runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java]: Then still you would have met the requirement for completing part of the quest, so my point still stands that if the req is met by doing the quest it shouldn't be a req on the diaries (unless its specific steal from x)

Comment (Nightfirecat) [reply runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/KandarinDiaryRequirement.java]: As I understand it, the thieving requirement for the quest is not a requirement for completion, only for the specific part of the quest which is needed for this diary.

File: runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java (hunk 2 above)
Comment (RyBo) [reply runelite-client/src/main/java/net/runelite/client/plugins/achievementdiary/diaries/WesternDiaryRequirement.java]: That's a good point, I removed that commit.
