### PR TITLE
Fix ExaminePlugin OOB exception

### LINKED ISSUE #294: Examine plugin - Out of bounds exception
Occurring randomly, or at least I do not found reason why is it happening. Probably just needs some array bounds check.

The exception is occurring for ids: 507, 508, 509, 510, 511, 487, 510, 511, 312, 276 (probably also few more). Here is example output: 

```
[Thread-7] WARN net.runelite.client.RuneliteModule - uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: 507
        at net.runelite.client.plugins.examine.ExaminePlugin.findExamineItem(ExaminePlugin.java:266)
        at net.runelite.client.plugins.examine.ExaminePlugin.onChatMessage(ExaminePlugin.java:214)
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at net.runelite.client.callback.Hooks.addChatMessage(Hooks.java:240)
        at ag.e(ag.java)
        at p.w(p.java)
        at client.gs(client.java)
        at client.ev(client.java)
        at client.aq(client.java)
        at be.p(be.java)
        at be.run(be.java)
        at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by UniquePassive**
Fixes #294 in the last changed code block and prevents NPE in the first two

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java [hunk 1]
```diff
@@ -252,20 +252,30 @@ else if (pendingExamine.getType() == ExamineType.ITEM_BANK_EQ)
...
+					itemId = widgetItem.getItemId();
+				}
 			}
 			else if (WidgetInfo.BANK_ITEM_CONTAINER.getGroupId() == widgetGroup)
 			{
-				Widget widgetItem = widget.getDynamicChildren()[pendingExamine.getActionParam()];
-				quantity = widgetItem != null ? widgetItem.getItemQuantity() : 1;
-				itemId = widgetItem.getItemId();
+				Widget[] children = widget.getDynamicChildren();
+				if (children.length > 0)
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java]: I guess you could also check ```pendingExamine.getActionParam()``` against the length too?
