### PR TITLE
ItemMapping: add Varlamore and Leagues 4 items

### LINKED ISSUE #17868: Charged/degradable items don't show GE value
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Some charged/degradable items do not have a GE value and do not contribute to total bank value when charged/degraded. Examples:
- Tonalztics of ralos
- Blazing blowpipe
- Ring of the elements
- Blue moon helm/chestplate/tassets

This is inconsistent with other items, such as:
- Toxic blowpipe
- Sanguinesti staff
- Barrows gear/crystal armour

Although these are not tradable when charged, their GE value does show up when hovering over them and total bank value.

### RuneLite version

RuneLite version: 1.10.30
Launcher version: 2.6.7

### Logs

_No response_

### PR DESCRIPTION
**Pull request by cdfisher**
Adds the following items:

-Tonalztics of Ralos
-Ring of the elements
-Trailblazer reloaded blowpipe ornament kit
-Blazing blowpipe
-Trailblazer reloaded bulwark ornament kit
-Dinh's blazing bulwark
-Blue moon armour
-Eclipse moon armour
-Blood moon armour
-Echo boots

Resolves #17868

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/game/ItemMapping.java [hunk 1]
```diff
@@ -252,6 +256,18 @@ public enum ItemMapping
...
+	// Lunar Chest armour
+	ITEM_BLUE_MOON_HELM(BLUE_MOON_HELM, BLUE_MOON_HELM_29041, BLUE_MOON_HELM_BROKEN),
+	ITEM_BLUE_MOON_CHESTPLATE(BLUE_MOON_CHESTPLATE, BLUE_MOON_CHESTPLATE_29037, BLUE_MOON_CHESTPLATE_BROKEN),
+	ITEM_BLUE_MOON_TASSETS(BLUE_MOON_TASSETS, BLUE_MOON_TASSETS_29039, BLUE_MOON_TASSETS_BROKEN),
+	ITEM_ECLIPSE_MOON_HELM(ECLIPSE_MOON_HELM, ECLIPSE_MOON_HELM_29035, ECLIPSE_MOON_HELM_BROKEN),
+	ITEM_ECLIPSE_MOON_CHESTPLATE(ECLIPSE_MOON_CHESTPLATE, ECLIPSE_MOON_CHESTPLATE_29031, ECLIPSE_MOON_CHESTPLATE_BROKEN),
+	ITEM_ECLIPSE_MOON_TASSETS(ECLIPSE_MOON_TASSETS, ECLIPSE_MOON_TASSETS_29033, ECLIPSE_MOON_TASSETS_BROKEN),
+	ITEM_BLOOD_MOON_HELM(BLOOD_MOON_HELM, BLOOD_MOON_HELM_29047, BLOOD_MOON_HELM_BROKEN),
+	ITEM_BLOOD_MOON_CHESTPLATE(BLOOD_MOON_CHESTPLATE, BLOOD_MOON_CHESTPLATE_29043, BLOOD_MOON_CHESTPLATE_BROKEN),
+	ITEM_BLOOD_MOON_TASSETS(BLOOD_MOON_TASSETS, BLOOD_MOON_TASSETS_29045, BLOOD_MOON_TASSETS_BROKEN),
```
Comment (Felanbird) [inline runelite-client/src/main/java/net/runelite/client/game/ItemMapping.java:270]: broken armor is tradable, the link is only needed for _##### untradeable version
```suggestion
	ITEM_BLUE_MOON_HELM(BLUE_MOON_HELM, BLUE_MOON_HELM_29041),
	ITEM_BLUE_MOON_CHESTPLATE(BLUE_MOON_CHESTPLATE, BLUE_MOON_CHESTPLATE_29037),
	ITEM_BLUE_MOON_TASSETS(BLUE_MOON_TASSETS, BLUE_MOON_TASSETS_29039),
	ITEM_ECLIPSE_MOON_HELM(ECLIPSE_MOON_HELM, ECLIPSE_MOON_HELM_29035),
	ITEM_ECLIPSE_MOON_CHESTPLATE(ECLIPSE_MOON_CHESTPLATE, ECLIPSE_MOON_CHESTPLATE_29031),
	ITEM_ECLIPSE_MOON_TASSETS(ECLIPSE_MOON_TASSETS, ECLIPSE_MOON_TASSETS_29033),
	ITEM_BLOOD_MOON_HELM(BLOOD_MOON_HELM, BLOOD_MOON_HELM_29047),
	ITEM_BLOOD_MOON_CHESTPLATE(BLOOD_MOON_CHESTPLATE, BLOOD_MOON_CHESTPLATE_29043),
	ITEM_BLOOD_MOON_TASSETS(BLOOD_MOON_TASSETS, BLOOD_MOON_TASSETS_29045),
```

**Review by Felanbird — APPROVED** [review]
I only have blue moon but it works

**Comment by sil3xz** [comment]
I forgot to mention Echo Boots, should have Guardian Boots value

File: runelite-client/src/main/java/net/runelite/client/game/ItemMapping.java [hunk 2]
```diff
@@ -296,6 +312,7 @@ public enum ItemMapping
 	ITEM_GHARZI_RAPIER(GHRAZI_RAPIER, HOLY_GHRAZI_RAPIER),
 	ITEM_MASTER_SCROLL_BOOK(MASTER_SCROLL_BOOK_EMPTY, MASTER_SCROLL_BOOK),
 	ITEM_ARCANE_SIGIL(ARCANE_SIGIL, ELIDINIS_WARD_F, ELIDINIS_WARD_OR),
+	ITEM_GUARDIAN_BOOTS(GUARDIAN_BOOTS, ECHO_BOOTS),
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/game/ItemMapping.java:315]: I wouldn't call this a "revertible item", as the echo crystal is lost when it is reverted. I think it would fit better under the "Degradable/charged weaponry/armour" section

**Review by Nightfirecat — CHANGES_REQUESTED** [review]
Can the commit history be cleaned up a bit? I'd expect varlamore equipment to be in one commit, league kits to be in another, and for ring of the elements to have its own commit.
