### PR TITLE
World Map: Identify Both Shield of Arrav Quest Start Points

### LINKED ISSUE #8437: Shield of Arrav quest start not mapped
**Describe the bug**
When hovering over the quest start icon on the map, the one for Charlie the Tramp, it only says Quest start when it should say Quest start - Shield of Arrav. Perhaps this is an issue because this quest has more than one start location. 

**To Reproduce**
1. Hover the quest start icon on the floating map
2. See that it says Quest start instead of Quest start - Shield of Arrav

**Expected behavior**
I expect to see Quest start - Shield of Arrav when I hover over this quest icon. 

**Screenshots**
https://imgur.com/a/X3HEsv6

**Environment**
 - OS: Windows
 - RuneLite version: 1.5.18
 - Launcher version: 1.6.0

### PR DESCRIPTION
**Pull request by xDemoN**
Closes #8437 

Let me know if you'd like the syntax to be different.

image

image

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/worldmap/QuestStartLocation.java [hunk 1]
```diff
@@ -46,7 +46,8 @@
 	THE_RESTLESS_GHOST("The Restless Ghost", new WorldPoint(3240, 3210, 0)),
 	RUNE_MYSTERIES("Rune Mysteries", new WorldPoint(3210, 3220, 0)),
 	SHEEP_SHEARER("Sheep Shearer", new WorldPoint(3190, 3272, 0)),
-	SHIELD_OF_ARRAV("Shield of Arrav", new WorldPoint(3208, 3495, 0)),
+	SHIELD_OF_ARRAV_1("Shield of Arrav (Phoenix Gang)", new WorldPoint(3208, 3495, 0)),
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/worldmap/QuestStartLocation.java]: Better enum names would be helpful here. `SHIELD_OF_ARRAV_PHOENIX_GANG` and `SHIELD_OF_ARRAV_BLACK_ARM_GANG` maybe?

**Comment by xDemoN** [comment]
Enum names updated @Nightfirecat
