### PR TITLE
Fix NPE on resetting configs with null default value

### LINKED ISSUE #12226: NullPointerException when resetting a default null config
Using a `Color` config option with an `@Alpha` that's default value is null throws a NPE when being reset.
It seems to unset the option but fails to show it in the config panel as unset.
<details>
  <summary>Stack trace</summary>

```java
[AWT-EventQueue-0] DEBUG net.runelite.client.config.ConfigManager - Unsetting configuration value for resourcepacks.colorPack
[AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NullPointerException
	at net.runelite.client.config.ConfigManager.objectToString(ConfigManager.java:706)
	at net.runelite.client.config.ConfigManager.setDefaultConfiguration(ConfigManager.java:577)
	at net.runelite.client.plugins.config.ConfigPanel.lambda$createResetMenuItem$13(ConfigPanel.java:669)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:980)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1024)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6650)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

### PR DESCRIPTION
**Pull request by paymon123**
None of the @Alpha default methods currently return null, so I changed the one in CannonConfig.java to replicate the exception.  Default method returning null behaves as though there is no default method, in both cases of individual reset and plugin-wide reset.

Fixes #12226

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonConfig.java [hunk 1]
```diff
@@ -89,10 +89,7 @@ default boolean showDoubleHitSpot()
 		description = "Configures the highlight color of double hit spots",
 		position = 5
 	)
-	default Color highlightDoubleHitColor()
```
Comment (raiyni) [inline runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonConfig.java:92]: Revert this change

**Comment by paymon123** [comment]
Is it that changing the alpha value of a color doesn't reflect as an alphahex in the panel?

File: runelite-client/src/test/java/net/runelite/client/config/ConfigManagerTest.java [hunk 2]
```diff
@@ -118,6 +118,21 @@ public void testGetConfigDescriptor() throws IOException
...
+		AccountSession accountSession = new AccountSession(UUID.randomUUID(), Instant.now());
+		accountSession.setUsername("test");
+
+		TestConfig conf = manager.getConfig(TestConfig.class);
+		ConfigDescriptor descriptor = manager.getConfigDescriptor(conf);
+		conf.nullDefaultKey("new value");
+
+		manager.unsetConfiguration(descriptor.getGroup().value(), "nullDefaultKey");
+		manager.setDefaultConfiguration(conf, false);
+		Assert.assertEquals(conf.nullDefaultKey(), null);
```
Comment (Nightfirecat) [inline runelite-client/src/test/java/net/runelite/client/config/ConfigManagerTest.java:136]:
```suggestion
		Assert.assertNull(conf.nullDefaultKey());
```

**Comment by Nightfirecat** [comment]
I've fixed the couple of issues here and squashed this into a single commit.
