### PR TITLE
Hide prayer flick indicator when minimap is hidden

### LINKED ISSUE #11133: Hide Minimap does not hide prayer flick timings
**Describe the bug**
When the hide minimap option is ticked, the prayer flick timer bar does not get hidden, leaving a blue bar on the screen.

**To Reproduce**
1. Ensure pray flick location in the Prayer plugin is set to prayer orb or both
2. Optionally enable never hide prayer flick helper (not required for the bug)
3. Enable hide minimap in the Minimap plugin

**Expected behavior**
Expected the blue pray flick bar to disappear along with the orbs and map

**Screenshots**
[Video](https://imgur.com/GcVA4EJ)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS] Windows 10 x64 LTSC (1809)
 - RuneLite version: [e.g 1.4.6] 1.6.11-SNAPSHOT
 - Launcher version: [e.g 1.5.2] 2.1.2-SNAPSHOT

### PR DESCRIPTION
**Pull request by rnoennig**
This fixes it, but I don't know about the difference between MINIMAP_PRAYER_ORB and MINIMAP_QUICK_PRAYER_ORB.

Fixes #11133

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickOverlay.java [hunk 1]
```diff
@@ -63,6 +63,12 @@ public Dimension render(Graphics2D graphics)
...
 		}
 
+		// Prayer orb widget will be hidden when minimap is hidden
+		Widget prayerOrb = client.getWidget(WidgetInfo.MINIMAP_PRAYER_ORB);
+		if (prayerOrb == null || prayerOrb.isHidden()) {
+			return null;
+		}
+
 		Widget xpOrb = client.getWidget(WidgetInfo.MINIMAP_QUICK_PRAYER_ORB);
 		if (xpOrb == null)
```
Comment (ThatGamerBlue) [inline runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickOverlay.java]: you can do ` || xpOrb.isHidden()` then you don't need the extra widget check

Comment (rnoennig) [reply runelite-client/src/main/java/net/runelite/client/plugins/prayer/PrayerFlickOverlay.java]: Thank you for your suggestion. I tested your code and it works fine for me. I have updated the PR.
