### PR TITLE
Item charges Plugin: Fix explorer's ring charges bug

### LINKED ISSUE #16550: [Item Charges] Explorer Ring charge count doesn't update on Check
### Type

Incorrect behavior

### Operating System

None

### OS Version

_No response_

### Bug description

Using the check option on the ring doesn't update the charges properly.  Only tested with explorers ring 4, I don't have access to other versions.

How to desync charge count for testing:
Turn off Item Charges plugin.
Use one or more alchemy charges on explorers ring.
Turn on Item Charges plugin.
Item Charges will still show the original number of charges. It properly updates after alchemy is used again.

### Screenshots or videos

image

### RuneLite version

1.9.15.3
2.6.3

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Fillz**
Close #16550

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java [hunk 1]
```diff
@@ -197,6 +197,8 @@ ItemChargeConfig getConfig(ConfigManager configManager)
 	protected void startUp()
 	{
 		overlayManager.add(overlay);
+		// Update explorer ring charges with value retrieved from varbit value
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java:200]: What does this comment clarify? This reads exactly the same as the following line, translated to a sentence.

**Comment by Fillz** [comment]
@Nightfirecat code updated. I no longer get the assertionError, so I assume it is now running on the correct thread.

File: runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java [hunk 2]
```diff
@@ -197,6 +197,7 @@ ItemChargeConfig getConfig(ConfigManager configManager)
 	protected void startUp()
 	{
 		overlayManager.add(overlay);
+		this.clientThread.invokeLater(this::updateExplorerRingChargesFromVarbit);
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java:200]: We typically don't use `this.` for referencing fields unless they are shadowed, so this can call `clientThread.invokeLater();` without the extra specifier.

Also, since this code is only called here, it can be an anonymous function instead, ex.

```java
clientThread.invokeLater(() ->
{
	updateExplorerRingCharges(client.getVarbitValue(Varbits.EXPLORER_RING_ALCHS));
});

Comment (Fillz) [reply runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java:200]: Very true, I'll fix that.

Comment (Fillz) [reply runelite-client/src/main/java/net/runelite/client/plugins/itemcharges/ItemChargePlugin.java]: Fixed now.

**Review by Nightfirecat — COMMENTED** [review]
LGTM. Let's wrap this in a game state check so that plugin startup doesn't fire configmanager warnings when not logged in / on the login screen. (getting the game state can run safely off-thread)

```java
if (client.getGameState() == GameState.LOGGED_IN)
{
	// ...
}
```

**Comment by Fillz** [comment]
@Nightfirecat Done.
