### PR TITLE
clues: make item requirements work with the runepouch

### LINKED ISSUE #11319: Clue Scroll plugin not detecting runes in runepouch for enchant dragonstone jewellery step
**Describe the bug**
When you have earth runes in your rune pouch and you have the enchant dragonstone jewellery clue step from an elite clue the plugin will not mark the earth runes with the green check in the overlay.

**To Reproduce**
1. Have elite clue with step "enchant dragonstone jewellery"
2. Have rune pouch in your inventory
3. Have earth runes, water or cosmic rune inside your rune pouch
4. You will not see the green check (it displays the red X) next to the requirement in the overlay

**Expected behavior**
The green check should be displayed in the overlay next to the runes if you have them in your rune pouch.

**Screenshots**
/

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: [e.g 1.6.11.1]
 - Launcher version: [e.g 1.6.2]

**Additional context**
/

### PR DESCRIPTION
**Pull request by Hydrox6**
Closes #11319

This makes it so the contents of the Runepouch are added to the inventory items, which allows them to be used in item requirements.

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 1]
```diff
@@ -318,6 +328,15 @@ public void onItemContainerChanged(final ItemContainerChanged event)
 
 		inventoryItems = event.getItemContainer().getItems();
 
+		for (Item i : inventoryItems)
+		{
+			if (i.getId() == ItemID.RUNE_POUCH || i.getId() == ItemID.RUNE_POUCH_L)
+			{
+				inventoryItems = ArrayUtils.addAll(inventoryItems, getRunepouchContents());
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java:335]: This doesn't look right to me. If I were to have an inventory containing a law rune, an air rune, and a rune pouch which contains four air runes, I'd get `inventoryItems = [ law, air, air x 4 ]` instead of the expected `[ law, air x 5 ]`

Comment (Hydrox6) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java:335]: Good point, I'll add some logic to combine the items

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 2]
```diff
@@ -318,6 +328,33 @@ public void onItemContainerChanged(final ItemContainerChanged event)
...
+				for (Item rune : runePouchContents)
+				{
+					if (invItem.getId() == rune.getId())
+					{
+						inventoryItems[i] = new Item(invItem.getId(), rune.getQuantity() + invItem.getQuantity());
+						runePouchContents.remove(rune);
+						break;
+					}
+				}
+				if (runePouchContents.size() <= 0)
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java:347]: Instead of being a `break` check, this can be incorporated into the loop condition:

```
for (int i = 0; i < inventoryItems.length && runePouchContents.size() > 0; i++)
```

**Comment by Nightfirecat** [comment]
Also if it's not too much work, a test for this would be handy. I don't know offhand if the various classes involved make adding a test for this a straightforward endeavor though.

**Comment by Hydrox6** [comment]
Updated with a test, please shout at me if it's wrong

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 3]
```diff
@@ -315,7 +325,31 @@ public void onItemContainerChanged(final ItemContainerChanged event)
 			return;
 		}
 
-		inventoryItems = event.getItemContainer().getItems();
+		// Clone the array so changes aren't passed back to the event.
+		inventoryItems = event.getItemContainer().getItems().clone();
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java:329]: This should probably only be copied if it going to add modifications

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 4]
```diff
@@ -315,7 +325,31 @@ public void onItemContainerChanged(final ItemContainerChanged event)
...
+					{
+						inventoryItems[i] = new Item(invItem.getId(), rune.getQuantity() + invItem.getQuantity());
+						runePouchContents.remove(rune);
+						break;
+					}
+				}
+			}
+			if (runePouchContents.size() > 0)
+			{
+				inventoryItems = ArrayUtils.addAll(inventoryItems, runePouchContents.toArray(new Item[]{}));
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java:350]:
```suggestion
				inventoryItems = ArrayUtils.addAll(inventoryItems, runePouchContents.toArray(new Item[0]))
```

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 5]
```diff
@@ -315,7 +323,31 @@ public void onItemContainerChanged(final ItemContainerChanged event)
...
+			List<Item> runePouchContents = getRunepouchContents();
+
+			for (int i = 0; i < inventoryItems.length && runePouchContents.size() > 0; i++)
+			{
+				Item invItem = inventoryItems[i];
+				for (Item rune : runePouchContents)
+				{
+					if (invItem.getId() == rune.getId())
+					{
+						inventoryItems[i] = new Item(invItem.getId(), rune.getQuantity() + invItem.getQuantity());
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java:340]: I guess this could overflow, but maybe it doesn't matter

Comment (Hydrox6) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java:340]: I could limit it if you think it's serious enough :man_shrugging:

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 6]
```diff
@@ -144,6 +146,12 @@
 		13150, 9011,
 		13151, 9012
 	};
+	private static final Varbits[] RUNEPOUCH_AMOUNT_VARBITS = {
+			Varbits.RUNE_POUCH_AMOUNT1, Varbits.RUNE_POUCH_AMOUNT2, Varbits.RUNE_POUCH_AMOUNT3
+		};
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java:151]:
```suggestion
		Varbits.RUNE_POUCH_AMOUNT1, Varbits.RUNE_POUCH_AMOUNT2, Varbits.RUNE_POUCH_AMOUNT3
	};
```

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 7]
```diff
@@ -144,6 +146,12 @@
...
+	private static final Varbits[] RUNEPOUCH_RUNE_VARBITS = {
+			Varbits.RUNE_POUCH_RUNE1, Varbits.RUNE_POUCH_RUNE2, Varbits.RUNE_POUCH_RUNE3
+		};
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java:154]:
```suggestion
		Varbits.RUNE_POUCH_RUNE1, Varbits.RUNE_POUCH_RUNE2, Varbits.RUNE_POUCH_RUNE3
	};
```
