### PR TITLE
music and chatcommands: fix several NPE

### LINKED ISSUE #13183: Music plugin NPE
Error found in someone else's logs:

```
2021-02-08 19:32:57 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.plugins.music.MusicPlugin$SettingsSideSlider.update(MusicPlugin.java:560)
	at net.runelite.client.plugins.music.MusicPlugin$Channel.update(MusicPlugin.java:827)
	at net.runelite.client.plugins.music.MusicPlugin.updateMusicOptions(MusicPlugin.java:852)
	at net.runelite.client.plugins.music.MusicPlugin.onVolumeChanged(MusicPlugin.java:302)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:73)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:222)
	at net.runelite.client.callback.Hooks.post(Hooks.java:161)
	at cd.lk(cd.java:25005)
	at gs.kg(gs.java:10679)
	at cs.kl(cs.java:10721)
	at client.pw(client.java:6297)
	at client.rn(client.java:2997)
	at client.ab(client.java:1256)
	at bd.ax(bd.java:351)
	at bd.run(bd.java:330)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by BossHuso**
Close #13183 #13160

Also fixed NPE in `SettingsSideSlider.shutdown()` when user disables "Granular volume sliders" on login screen.

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java [hunk 1]
```diff
@@ -588,7 +593,11 @@ public void update()
 		public void shutDown()
 		{
 			super.shutDown();
-			handle.setSpriteId(SpriteID.SETTINGS_SLIDER_HANDLE_BLUE);
+
+			if (this.handle != null)
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java:597]: I don't see any errors relating to the handle. What is this updated for?

Comment (BossHuso) [reply runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java:597]: Noticed in my own logs, happens when u toggle "Granular volume sliders" on the login screen.
