### PR TITLE
Fix minor spelling error in Kourend Library plugin

### LINKED ISSUE #1515: Kourend Library Plugin bug
Tradgedy is written with a grammar error and also, the wrong location is written on the right hand menu.
image

### PR DESCRIPTION
**Pull request by Gamer1120**
Partly fixes #1515

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You may need to rename your commit so it does not close #1515 automatically. (eg. `Partial fix for #1515`)

File: runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Book.java [hunk 1]
```diff
@@ -147,4 +147,4 @@ private static BufferedImage getImage(String name)
 			throw new RuntimeException("Cannot load book " + name, e);
 		}
 	}
-}
\ No newline at end of file
+}
```
Comment (devLotto) [inline runelite-client/src/main/java/net/runelite/client/plugins/kourendlibrary/Book.java]: What's this?
