### PR TITLE
client: fix spec bar not updating with hide auto retaliate on

### LINKED ISSUE #7851: Hidden auto retaliate messes with the special attack bar
**Describe the bug**
When hiding the auto retaliate button and then use the special attack button, the special attack bar freezes (stays visually full). https://i.imgur.com/p2deOkD.png 

Also, when enabling the "hide auto retaliate" option for the first time, the special attack bar was removed completely. Turning "hide auto retaliate" off and back on fixes this issue, but the visuals of the special attack bar do not change unless the "Hide auto retaliate button" is turned off-on.

**To Reproduce**
Steps to reproduce the behaviour:
-Hide auto retaliate button in the attack styles plugin (spec bar disappears if turned on for the first time)
-Use special attack (e.g. dragon axe special attack)
-Watch the special attack bar (the % left will not change)

**Expected behaviour**
The special attack bar should visually represent the % of the special attack power left. 

**Environment:**

* RuneLite version: [e.g 1.5.12]

### PR DESCRIPTION
**Pull request by Adam-**
Move the widget listener from the auto retaliate text to the spec bar,
so when auto retaliate is hidden the listeners still function.

Fixes #7851

### CODE REVIEW

File: runelite-api/src/main/java/net/runelite/api/widgets/WidgetInfo.java [hunk 1]
```diff
@@ -313,6 +313,7 @@
 	COMBAT_SPELL_ICON(WidgetID.COMBAT_GROUP_ID, WidgetID.Combat.SPELL_ICON),
 	COMBAT_SPELL_TEXT(WidgetID.COMBAT_GROUP_ID, WidgetID.Combat.SPELL_TEXT),
 	COMBAT_AUTO_RETALIATE(WidgetID.COMBAT_GROUP_ID, WidgetID.Combat.AUTO_RETALIATE),
+	COMBAT_SPEC_BAR(WidgetID.COMBAT_GROUP_ID, WidgetID.Combat.SPEC_BAR),  // Used by overriden script 327
```
Comment (abextm) [inline runelite-api/src/main/java/net/runelite/api/widgets/WidgetInfo.java]:
```suggestion
	COMBAT_SPEC_BAR(WidgetID.COMBAT_GROUP_ID, WidgetID.Combat.SPEC_BAR),  // Used by CombatInterfaceSP.rs2asm
```
