### PR TITLE
Fix sidebar hotkey leaking into game client

### LINKED ISSUE #4945: Upon pressing CTRL-F11 to open/close the sidebar, don't send an F11 input to the game.
When you open or close the sidebar using CTRL-F11, an F11 is triggered in-game, opening whatever menu you have F11 bound to. In an ideal world, this would not happen.

### PR DESCRIPTION
**Pull request by rbbi**
Fixes #4945

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java [hunk 1]
```diff
@@ -290,7 +294,15 @@ public void open(final RuneLite runelite) throws Exception
...
 
 			// Add key listener
-			final UiKeyListener uiKeyListener = new UiKeyListener(this);
+			final HotkeyListener uiKeyListener = new HotkeyListener(() ->
+				new Keybind(KeyEvent.VK_F11, InputEvent.CTRL_DOWN_MASK))
+			{
+				@Override
+				public void hotkeyPressed()
+				{
+					SwingUtilities.invokeLater(() -> toggleSidebar());
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java]: No need for invokeLater, it should already be in Swing thread

File: runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java [hunk 2]
```diff
@@ -290,7 +294,15 @@ public void open(final RuneLite runelite) throws Exception
...
+				}
+			};
 			frame.addKeyListener(uiKeyListener);
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java]: add empty line above
