### PR TITLE
Fix the game freezing when screenshots are being taken

### LINKED ISSUE #602: Game freezes for a moment when the screenshot plugin takes a screenshot
This is fine if I'm fishing, not quite as fine when I'm in combat.

### PR DESCRIPTION
**Pull request by devLotto**
Fixes #602

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java [hunk 1]
```diff
@@ -100,6 +102,8 @@
 
 	private static final Pattern NUMBER_PATTERN = Pattern.compile("([0-9]+)");
 
+	private static final ExecutorService IMAGE_SAVING_POOL = Executors.newCachedThreadPool();
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java]: Why not use the existing executor?
