### PR TITLE
Fix null names for quest objects in cryptic clues

### LINKED ISSUE #1926: Object null on Spirit Tree in Tree Gnome Village clue
image

### PR DESCRIPTION
**Pull request by deathbeam**
Example: Spirit Tree NULL_1293.

Fixes #1926
Closes #3480

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java [hunk 1]
```diff
@@ -358,6 +359,11 @@ public void makeOverlayHint(PanelComponent panelComponent, ClueScrollPlugin plug
 		{
 			ObjectComposition object = plugin.getClient().getObjectDefinition(getObjectId());
 
+			if (Strings.isNullOrEmpty(object.getName()) || "null".equals(object.getName()))
+			{
+				object = object.getImpostor();
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java]: Line 361 implies object can be null. Also do not call getImpostor without first checking impostorids is not null.
