### PR TITLE
Fix ToB door quick-enter swap and add a test for it

### LINKED ISSUE #10553: Quick-enter : Enter menu swap in ToB doesn't work with some configurations
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Quick-enter : Enter menu swap in ToB doesn't work with some configurations.

**To Reproduce**
Have the Home swap set to Home and the Quick Pass/Open/Start/Travel set to true.
Expected: Quick-enter becomes the top menu entry for the door to go to the next room in ToB.
Actual: The swap isn't performed and Enter is still the top menu entry.

### PR DESCRIPTION
**Pull request by melkypie**
Fixes #10553 and adds a test

### CODE REVIEW

File: runelite-client/src/test/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPluginTest.java [hunk 1]
```diff
@@ -263,4 +263,61 @@ public void testTeleport()
 			menu("Cast", "Varrock Teleport", MenuAction.WIDGET_SECOND_OPTION),
 		}, argumentCaptor.getValue());
 	}
+
+	@Test
+	public void testTobDoor()
+	{
+		when(config.swapQuick() && config.swapHomePortal() != HouseMode.ENTER).thenReturn(true);
```
Comment (Adam-) [inline runelite-client/src/test/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPluginTest.java]: You can't put expressions inside of when(), I'm surprised this works at all

Comment (melkypie) [reply runelite-client/src/test/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPluginTest.java]: Changed the test a bit
