### PR TITLE
Fix clue resetting

### LINKED ISSUE #1966: Clue step info doesn't always update
Sometimes when doing a Clue Scroll (Medium, not sure about the other Clue Scrolls) the information does not update to show what you need to do for the next step. I found this occurs the most often with clues that involve digging in a certain location.

### PR DESCRIPTION
**Pull request by deathbeam**
- Save last item ID on either map clue or when reading regular clue
- If this item is removed from inventory reset clue
- If we opened clue but it is uknown simply reset clue overlay

Fixes #1966

Preview:
peek 2018-04-23 21-52

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 1]
```diff
@@ -116,6 +118,9 @@
 	@Inject
 	private ClueScrollWorldOverlay clueScrollWorldOverlay;
 
+	private Integer clueItem;
```
Comment (devLotto) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java]: I'd prefer "clueItemId"
