### PR TITLE
Fix tray icon crash when clicked quickly on start

### LINKED ISSUE #1130: Client crashed when you click on the tray icon before it is fully loaded
The client doesn't like it when you press the system tray icon before the client is loaded.

error
```
java.lang.ArrayIndexOutOfBoundsException: 102510
	at ab.x(ab.java:1118)
	at client.ah(client.java:920)
	at bh.h(bh.java:369)
	at bh.copy$run(bh.java:323)
	at bh.run(bh.java:60)
	at java.lang.Thread.run(Thread.java:748)
```

And then this happens, the client does not start
error_2

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at net.runelite.client.ui.ClientUI.show(ClientUI.java:344)
	at net.runelite.client.RuneLite.start(RuneLite.java:187)
	at net.runelite.client.RuneLite.main(RuneLite.java:122)
Caused by: java.awt.IllegalComponentStateException: The frame is displayable.
	at java.awt.Frame.setUndecorated(Frame.java:923)
	at net.runelite.client.ui.ClientUI.lambda$show$8(ClientUI.java:346)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Reproduce:
1. Start the client
2. Wait for the tray icon to appear and click on it

OS: Windows 10
Java: 8_162

### PR DESCRIPTION
**Pull request by JustANull**
`SwingUtil` adds a click event to focus the frame, but the frame isn't fully built when the icon is created. Clicking after the icon was made and before the frame was built caused a crash. Moved the icon creation to after the frame is built, should resolve the problem. Fixes #1130.

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java [hunk 1]
```diff
@@ -399,6 +397,8 @@ public void layoutContainer(Container parent)
 			frame.toFront();
 			requestFocus();
 			giveClientFocus();
+
+			trayIcon = SwingUtil.createTrayIcon(ICON, properties.getTitle(), frame);
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java]: This will probably cause the Notifier to be initialized with null tray icon, so tray notifications will stop working

Comment (JustANull) [reply runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java]: I checked just to be sure, and it doesn't. Started up the game, logged in, attacked a cow, got an idle notification after it died.

The only time `getTrayIcon` is called is in `sendTrayNotification`, and it doesn't store the result. It just ignores the potential notification if it returns `null`, and it's unlikely to anyways as AFAIK RuneLite doesn't send any notifications on startup.

Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java]: Ah, my mistake, I forgot that there was change in the ClientUI and notifier to make them created by guice, so yea it should be fine now.
