### PR TITLE
Fix XP Drop plugin recolouring ALL drops whenever a combat prayer is enabled

### LINKED ISSUE #555: Colored xp drops for non-combat skills while using prayer
Non-combat experience drops are colored while using combat prayers.
Example: Using Piety while Woodcutting gives a colored Woodcutting xp drop.

From Apo in Discord:
> Is it intended that prayer xp drop recolor also recolors noncombat stats?
> Like, I can pray flick while wcing and get recolored wc xp drops

### PR DESCRIPTION
**Pull request by SoyChai**
This fixes #555.

Plugin wasn't actually checking whether the XP drop widgets were for the relevant combat skill before recolouring them, so I've added their SpriteIDs to verify the skill icons as they appear.

Both grouped and ungrouped XP drops work as expected now.

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java [hunk 1]
```diff
@@ -85,20 +91,38 @@ public void onWidgetHidden(WidgetHiddenChanged event)
 		}
 
 		String text = widget.getText();
+		final Stream<Widget> siblingWidgets = Arrays.stream(widget.getParent().getDynamicChildren());
+		final List<Integer> spriteIDs = siblingWidgets.map(Widget::getSpriteId).collect(Collectors.toList());
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java]: Why not just leave this as stream? It will be used only once anyway.

File: runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java [hunk 2]
```diff
@@ -85,20 +91,38 @@ public void onWidgetHidden(WidgetHiddenChanged event)
...
+
 		if (text != null)
 		{
+			int color = widget.getTextColor();
+
 			switch (prayer)
 			{
 				case MELEE:
-					widget.setTextColor(config.getMeleePrayerColor().getRGB());
+					if (spriteIDs.contains(SpriteID.SKILL_ATTACK)
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java]: Leave previous variable as stream and use .filter(predicate).findAny().isPresent()

**Comment by SoyChai** [comment]
What about them? If an attack drops XP for any reason, it can be caught.

File: runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java (hunk 1 above)
Comment (SoyChai) [reply runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java]: I've knocked out the unnecessary List in the middle, thanks for the advice.

**Comment by EvanWalden** [comment]
Sorry, I misunderstood your code.

File: runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java [hunk 3]
```diff
@@ -37,6 +38,9 @@
 import net.runelite.client.plugins.Plugin;
 import net.runelite.client.plugins.PluginDescriptor;
 
+import java.util.Arrays;
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java]: Fix your import order

File: runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java [hunk 4]
```diff
@@ -85,20 +89,37 @@ public void onWidgetHidden(WidgetHiddenChanged event)
 		}
 
 		String text = widget.getText();
+		final IntStream spriteIDs =
+			Arrays.stream(widget.getParent().getDynamicChildren()).mapToInt(Widget::getSpriteId);
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java]: You most likely do not need int stream at all, can't you like just `map` it instead?

File: runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java (hunk 3 above)
Comment (SoyChai) [reply runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java]: Fixed, amended the commit.

File: runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java (hunk 4 above)
Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropPlugin.java]: Hmm, maybe, idk to me it feels like unnecessary transformation. But if it does not have downsides, then its ok I guess.
