### PR TITLE
Fix til next level time for low xp amounts

### LINKED ISSUE #2984: When XP per hour < 3600, actions remaining is infinite
When training a skill, especially for low xp events, xp per second is 0 because xp per hour / 3600 rounds down.

image

I plan to fix this but I'll create an issue to document

### PR DESCRIPTION
**Pull request by LeviSchuck**
Cause:
Time til next level relied on xp per hour being divided by 3600
(seconds in an hour). For XP rates under 3600 per hour, this would
result in a divide by zero.
image

Another bug was that if the time was > 24 hours, it would roll over and say 1 hour remaining for 25 hours more training.

Solution:
Simplify the mathematical expression to not use fractional divisions, use custom string formatting

It appears to work as expected.
image

Fixes #2984

### CODE REVIEW

**Comment by LeviSchuck** [comment]
Thanks for the review Deathbeam. I just noticed another problem, if the time is > 24 hours, it will show a modulo of one day.

**Comment by LeviSchuck** [comment]
Incoming change:
image
This should help any level 98's :)

File: runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java [hunk 1]
```diff
@@ -120,11 +123,43 @@ int getSkillProgress()
...
+		// formula is xpRemaining / xpPerSecond
+		// xpPerSecond being xpGained / seconds
+		// This can be simplified so division is only done once and we can work in whole numbers!
+		long remainingSeconds = (getXpRemaining() * seconds) / xpGained;
+
+		// Java 8 doesn't have good duration / period objects to represent spans of time that can be formatted
+		// Rather than importing another dependency like joda time (which is practically built into java 10)
+		// below will be a custom formatter that handles spans larger than 1 day
+
+		long durationDays = remainingSeconds / 86400;
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpStateSingle.java]: Instead of 86400 i would use (24 * 60 * 60) for the sake of readability
