### PR TITLE
Monkey woodcutting fixes

### LINKED ISSUE #547: The woodcutting overlay thinks I'm not woodcutting when I'm a monkey
I'm not sure if there's actually a way to solve this, since the overlay is using the player's animation to figure out if there's any woodcutting going on, but it doesn't look like there's any animation for woodcutting while you're a monkey.
2018-02-08-000109_555x507_scrot

### PR DESCRIPTION
**Pull request by YvesW**
Fixes monkey woodcutting:
- idle notifier (closes #547)
- woodcutting overlay when chopping trees as a monkey

The following videos were recorded before I split the varp changes into a separate commit, so the group bonus is not included in this PR anymore.
Before:
https://streamable.com/eo2rjo

After:
https://streamable.com/to6dh2

A separate commit is used for the VarPlayer changes so I could also use that commit in https://github.com/runelite/runelite/pull/17219

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java [hunk 1]
```diff
@@ -103,6 +104,7 @@ public class IdleNotifierPlugin extends Plugin
 	private Instant sixHourWarningTime;
 	private boolean ready;
 	private boolean lastInteractWasCombat;
+	private static final int buffBarNotDisplayed = -1;
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java:107]: By convention, static final fields are always UPEPRCASE. Or just inline the -1 since it does not really matter.

File: runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java [hunk 2]
```diff
@@ -40,6 +41,7 @@
 class WoodcuttingOverlay extends OverlayPanel
 {
 	private static final String WOODCUTTING_RESET = "Reset";
+	private static final int buffBarDisplayed = 96;
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/woodcutting/WoodcuttingOverlay.java:44]: see above comment

**Review by Adam- — CHANGES_REQUESTED** [review]

File: runelite-api/src/main/java/net/runelite/api/VarPlayer.java [hunk 3]
```diff
@@ -240,4 +240,11 @@ public final class VarPlayer
 	 * Assigned slayer task location. The mapping of value to name can be found in {@link EnumID#SLAYER_TASK_LOCATION}
 	 */
 	public static final int SLAYER_TASK_LOCATION = 2096;
+
+	/**
+	 * Determines whether the woodcutting group bonus should be displayed on the buff bar or not.
+	 * 96 = displayed (including the woodcutting guild).
+	 * -1 = not displayed (including normal trees or trees grown through farming).
```
Comment (Nightfirecat) [inline runelite-api/src/main/java/net/runelite/api/VarPlayer.java:247]: varp 4007 is also 0 on login, and until you begin woodcutting

**Review by Nightfirecat — COMMENTED** [review]
LGTM besides the minor javadoc note

File: runelite-api/src/main/java/net/runelite/api/VarPlayer.java (hunk 3 above)
Comment (YvesW) [reply runelite-api/src/main/java/net/runelite/api/VarPlayer.java:248]: Thank you very much for the review! I've amended the javadoc.
