### PR TITLE
slayer: display wilderness slayer task streak

### LINKED ISSUE #7329: Slayer task counter should track wilderness streak separately
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
We have two kinds of slayer masters. The normal ones, and [Krystillia](https://oldschool.runescape.wiki/w/Krystilia). Assignments from Krystilia have a separate task completion counter to standard assignments. Although they are counted separately, players cannot have a regular and Wilderness slayer task at the same time.

The completion counter does not support this. After you complete a krystillia task, runelite will remember the task count (for example: 15). If you then complete a task from any other master, for example Chaeldar, it will show your normal task count again (for example: 97).

**To Reproduce**
1. Get task from Chaeldar
2. Complete slayer task. Runelite will remember streak count (i.e. 97)
3. Get task from Krystillia. (Runelite thinks your streak count is 97).
4. Complete task. You have now completed 12 tasks in the wilderness. Runelite reads the red text and now thinks your streak is 12.
5. Get task from Chaeldar again.
6. Complete task. Runelite updates your slayer task streak again and now thinks you have 98 tasks completed.

**Expected behavior**
Keep a seperate record for both slayer streaks. A standard and a wilderness one. If your task is given by Krystillia, you are working on your wilderness slayer streak. Any other slayer master is the standard streak.

A suggestion is to also clarify your current task is from Krystillia. Append `(Wilderness)` or a `(skull)` to the monster name? 
image

**Screenshots**
After completing my Trolls task from Chaeldar:
image
My new task from Krystillia:
image

image

When I finish my black demon task I will update this post with more information.

image

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.7 (latest)
 - Launcher version: Unknown

### PR DESCRIPTION
**Pull request by YvesW**
Displays the wilderness slayer task streak if the player has a wilderness slayer task.

Spiritual creatures wildy task:
runelite/master
image

runelite/krystilia-task-streak
image

Closes #7329

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java [hunk 1]
```diff
@@ -338,22 +338,26 @@ public void onVarbitChanged(VarbitChanged varbitChanged)
 		{
 			clientThread.invokeLater(this::updateTask);
 		}
-		else if (varbitId == Varbits.SLAYER_POINTS)
+		else if (varbitId == Varbits.SLAYER_POINTS || varbitId == Varbits.SLAYER_TASK_STREAK || varbitId == Varbits.SLAYER_WILDERNESS_TASK_STREAK || varbitId == Varbits.SLAYER_MASTER)
```
Comment (zachtyll) [inline runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java:341]: This can be formatted like the if-clause above for improved readability.

File: runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java [hunk 2]
```diff
@@ -655,8 +661,9 @@ private void addCounter()
 				+ " " + initialAmount;
 		}
 
+		int streak = getIntProfileConfig(SlayerConfig.SLAYER_MASTER_KEY) == 7 ? getIntProfileConfig(SlayerConfig.WILDERNESS_STREAK_KEY) : getIntProfileConfig(SlayerConfig.STREAK_KEY);
```
Comment (zachtyll) [inline runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java:664]: I assume the `7` here means Krystilia, as commented in `Varbits.java`. Using an enum instead of a "magic number" would significantly improve the maintainability of this code.

**Review by zachtyll — COMMENTED** [review]
I've read through the code. There are some changes that could improve maintainability of the code. I also left some nitpicks.

I did not test these changes in "production" by running the client.

File: runelite-api/src/main/java/net/runelite/api/Varbits.java [hunk 3]
```diff
@@ -818,12 +818,28 @@ public final class Varbits
...
+	public static final int SLAYER_WILDERNESS_TASK_STREAK = 5617;
 
 	/**
 	 * The assigned boss for boss slayer.
 	 */
 	public static final int SLAYER_TASK_BOSS = 4723;
 
+	/**
+	 * The slayer master that assigned the task. Varbit does not get reset to 0 after task completion.
+	 * <p>
```
[the remark this answers is not in the document]
Comment (YvesW) [reply runelite-api/src/main/java/net/runelite/api/Varbits.java:830]: The same thing as it does [here](https://github.com/runelite/runelite/blob/3f4bb46931e54db2d281221663ed84fce4311dbe/runelite-api/src/main/java/net/runelite/api/Varbits.java#L700C8-L700C8) or [here](https://github.com/runelite/runelite/blame/3f4bb46931e54db2d281221663ed84fce4311dbe/runelite-api/src/main/java/net/runelite/api/Varbits.java#L781)

File: runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java (hunk 1 above)
Comment (YvesW) [reply runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java]: That's very true; accidentally missed this.

File: runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java (hunk 2 above)
Comment (YvesW) [reply runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java:667]: I thought it was fine before since it is explained in ``Varbits.java``,the plugin already contains [this](https://github.com/runelite/runelite/blame/664d479fdc646dee1adb3e7b910ff81adbf9af8d/runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java#L379), and it was only used once. Added it a static final int for now.

**Review by zachtyll — APPROVED** [review]
LGTM

File: runelite-api/src/main/java/net/runelite/api/Varbits.java [hunk 4]
```diff
@@ -818,12 +818,28 @@ public final class Varbits
...
+	 * 0 = no slayer master
```
Comment (Nightfirecat) [inline runelite-api/src/main/java/net/runelite/api/Varbits.java:831]: Would you mind updating this list such that lines have breaks inserted (eg. add `<br>` at the end of these lines so the javadoc won't just render newlines as spaces) and with post-wgs slayer master names

File: runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java [hunk 5]
```diff
@@ -338,22 +341,29 @@ public void onVarbitChanged(VarbitChanged varbitChanged)
...
+					break;
+				case Varbits.SLAYER_TASK_STREAK:
+					setProfileConfig(SlayerConfig.STREAK_KEY, varbitValue);
+					break;
+				case Varbits.SLAYER_WILDERNESS_TASK_STREAK:
+					setProfileConfig(SlayerConfig.WILDERNESS_STREAK_KEY, varbitValue);
+					break;
+				case Varbits.SLAYER_MASTER:
+					setProfileConfig(SlayerConfig.SLAYER_MASTER_KEY, varbitValue);
+					break;
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java:363]: If this var value persists after a task is assigned, why do we save it to config?

Comment (YvesW) [reply runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java:363]: That's a good question. At the time of writing this PR, I very likely looked at the other varbits in the plugin (points, streak), which are also saved to the config, and assumed there was a good reason they were saved to the config. At least the points are also available after a task is completed as far as I can tell (tested on QSR), just like the slayer master.

If you'd like me to change this, and potentially do the same for points and/or streak, please let me know.

I'm not 100% sure if the streak is also always persistent. Currently on QSR it seems to be that way, but ``client.getVarbitValue(5671)`` shows that my wilderness task streak (non-QSR) is 0 while I'm on a regular task, which should be incorrect since I've done a bit of wilderness slayer (see screenshot of the original post) without ever turael skipping.

Comment (raiyni) [reply runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java:364]: I would assume it's a relic from before they sent all of the slayer information as varbits? It looks to be the case https://github.com/runelite/runelite/commit/1f6ae893d732cf3a022fe6d9662cd2a42ff2b217

Comment (YvesW) [reply runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java]: That seems to be the case indeed. Based on the brief discussion on Discord, I've removed saving the slayer master varb. During the next beta I might be able to test if the rest of the varbs and varps are persistent or not, potentially for a separate PR if this one would have already been merged (assuming we're even interested in removing them from the config).
