### PR TITLE
Fix "Only show loot" ground items

### LINKED ISSUE #6843: Drops from Abyssal Sire don't show up when using "Only show loot" option
No drops show up with Ground Items when killing the Abyssal Sire with `Only show loot` enabled

**To Reproduce:**
1. Enable `Ground Items` and `Only show loot`
2. Go to Sire
3. Kill Sire
4. Wonder why your Onyx Bolt Tips didn't show up

**Environment:**
 - RuneLite version: 1.5.3

### PR DESCRIPTION
**Pull request by TheStonedTurtle**
Fixes #6843

### CODE REVIEW

**Comment by TheStonedTurtle** [comment]
Release: 
#6842: 

Thanks to @Hydrox6 for testing.

File: runelite-client/src/main/java/net/runelite/client/game/ItemStack.java [hunk 1]
```diff
@@ -25,10 +25,12 @@
...
 
 import lombok.Value;
+import net.runelite.api.coords.LocalPoint;
 
 @Value
 public class ItemStack
 {
 	private final int id;
 	private final int quantity;
+	private final LocalPoint point;
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/game/ItemStack.java]: Rename this to location

**Comment by TheStonedTurtle** [comment]
Renamed to Location and stopped accounting for instance on WorldPoint since `tile.getWorldLocation()` doesn't account for it either.
