### PR TITLE
Do not use object world locations for clues

### LINKED ISSUE #1314: Clue scroll plugin highlights every matching GameObject.
For example:
4 Bookcases
Only 1 bookcase should be highlighted, but it selects them all.

Not sure exactly what information is required to fix this.
I'm assuming it needs to be fixed per step? If so, I can try and help grab Clue scroll ID and Coordinates of the GameObjects when I get these clues.

### LINKED ISSUE #1692: Clue helper points at the wrong crate (medium, clocktower map clue)
image

### LINKED ISSUE #1732: Cryptic clue Varrock Castle crate wrong highlight
title 
image

### PR DESCRIPTION
**Pull request by deathbeam**
- Instead of using object world locations and using query to find
objects, if object clue also has location, just find all objects on tile
on that clue's location and check if ID is matching
- Fix varrock west bank cryptic clue (what was used also during testing)

Fixes #1692 and fixes #1314 and fixes #1732 

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 1]
```diff
@@ -217,11 +220,31 @@ public void onGameTick(final GameTick event)
...
+
+						objectsToMark = Arrays.stream(tile.getGameObjects())
+							.filter(object -> object != null && object.getId() == objectId)
+							.toArray(GameObject[]::new);
+					}
+				}
+				else
+				{
+					// All data we have is object id, so try to at least mark something
+					objectsToMark = queryRunner.runQuery(new GameObjectQuery().idEquals(objectId));
```
Comment (devLotto) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java]: There are no ObjectClueScrolls that aren't also LocationClueScrolls, so this else has no use.

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java [hunk 2]
```diff
@@ -217,11 +220,31 @@ public void onGameTick(final GameTick event)
 
 			if (objectId != -1)
 			{
-				GameObjectQuery query = new GameObjectQuery().idEquals(objectId);
-				objectsToMark = queryRunner.runQuery(query);
+				if (clue instanceof LocationClueScroll)
+				{
+					// Match object with location every time
+					final WorldPoint location = ((LocationClueScroll) clue).getLocation();
+					LocalPoint localLocation = LocalPoint.fromWorld(client, location);
```
Comment (devLotto) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java]: Doesn't this result in an NPE on clues that are missing a location (getLocation() returns null)?

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java [hunk 3]
```diff
@@ -30,22 +30,47 @@
...
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_3596;
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_3598;
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_3599;
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_3601;
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_3602;
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_7286;
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_7288;
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_7290;
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_7292;
+import static net.runelite.api.ItemID.CLUE_SCROLL_MEDIUM_7294;
```
Comment (devLotto) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/MapClue.java]: Not sure if removing the star import is warranted. We don't have all map clues, so this list of imports will be quite long in the end I think.

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java (hunk 1 above)
Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java]: Yeah, I know, but it is just in case.

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java (hunk 2 above)
Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java]: Yes it does, oops.

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java (hunk 1 above)
Comment (devLotto) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java]: Just in case Jagex adds another clue type? Umm...

Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScrollPlugin.java]: Just in case someone will forget/dont have data about location, only the object ID for w/e reason. It's mostly just so we will see at least something and not just wonder why clue is not highlighting anything in future. Idk, it do not hurts to have it, even though the scenario where it will apply is not that realistic.
