### PR TITLE
Fix panel expanding inconsistency

### LINKED ISSUE #463: "Game size" width is inconsistent
1) Set the width in client
2) Restart the client
3) Client width is smaller

Caused by the settings panel taking up space while setting the width, but not when the client is launched. Maybe the width should include the settings panel?

Settings:
image

After setting, before restart:
image

After restart
image

### PR DESCRIPTION
**Pull request by Kamielvf**
Make the panel actually expand outwards of the client instead of inwards. Fixes inconsistency of game size.

Fixes #463

### CODE REVIEW

**Comment by UniquePassive** [comment]
If you position the client window at the right edge of your monitor, and then open the sidebar, it'll grow inwards. When you then remove the sidebar, the window will be smaller than it was in the start. Is it possible you could fix that too?

https://i.imgur.com/KRRojyV.gifv

**Comment by Kamielvf** [comment]
Thanks, missed out on that but should be fixed now.

File: runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java [hunk 1]
```diff
@@ -397,6 +399,14 @@ void expand(PluginPanel panel)
 		{
 			navContainer.remove(0);
 		}
+		else
+		{
+			clientSize = this.getSize();
+			if (isInScreenBounds((int) getLocationOnScreen().getX() + getWidth() + PANEL_EXPANDED_WIDTH, (int) getLocationOnScreen().getY()))
```
Comment (SomeoneWithAnInternetConnection) [inline runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java]: Is there a specific reason for using `(int) getLocationOnScreen().getX()` rather than `getLocationOnScreen().x`? `java.awt.Point`s seem to have an integer `x` field
