### PR TITLE
loot tracker: capture unique wintertodt rewards

### LINKED ISSUE #18687: [Loot Tracker] Wintertodt cart loot does not track uniques
### Type

Incorrect behavior

### Operating System

None

### OS Version

_No response_

### Bug description

When pulling rewards from the Wintertodt cart, uniques do not display in the loot tracker.
The text for uniques is colored while the regular loot is not.

Relevant commit: https://github.com/runelite/runelite/commit/7dd96d7868fc7606b1c86e4218201c735b23b3c4

### Screenshots or videos

Image

### RuneLite version

RuneLite Version: 1.10.48
Launcher: 2.7.1

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Macweese**
This PR resolves an uncaught case within the loot tracker plugin, when collecting Wintertodt rewards.
A test for Wintertodt loot tracking was also added.

```
2025-02-23 15:40:07 CET [Client] DEBUG injected-client - Chat message type SPAM: <col=ef1020>You found some loot: 17 x Burnt page
2025-02-23 15:40:07 CET [Client] DEBUG n.r.c.p.l.LootTrackerPlugin - Inv change: [ItemStack(id=20718, quantity=17)] Ground items: []

2025-02-23 15:47:15 CET [Client] DEBUG injected-client - Chat message type SPAM: You found some loot: 4,694 x Coins
2025-02-23 15:47:15 CET [Client] DEBUG n.r.c.p.l.LootTrackerPlugin - Inv change: [ItemStack(id=995, quantity=4694)] Ground items: []
```

The reward message for rare loot is identical on both opaque and transparent chats.

<details>
  <summary>Spoiler</summary>
  
image
image

</details>

Fixes #18687

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java [hunk 1]
```diff
@@ -278,7 +278,7 @@ public class LootTrackerPlugin extends Plugin
 
 	private static final String WINTERTODT_SUPPLY_CRATE_EVENT = "Supply crate (Wintertodt)";
 	private static final String WINTERTODT_REWARD_CART_EVENT = "Reward cart (Wintertodt)";
-	private static final String WINTERTODT_LOOT_STRING = "You found some loot: ";
+	private static final Pattern WINTERTODT_LOOT_PATTERN = Pattern.compile("(<col=ef1020>)?You found some loot: ");
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java:281]: The optional leading color tag does nothing, because the "You found some loot: " string would still be matched. See: the burnt pages test you added which uses `<col=af1020>` (**a**, not *e*) which still passes.

Comment (Nightfirecat) [reply runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java:281]: Generally instead of using fixed hex colors we will match `[0-9a-f]{6}` as these sometimes differ between opaque and transparent chat backgrounds.
