### PR TITLE
Bug: Adds the Twisted Slayer Helmet to the Kill a Dustdevil Skill Clue

### LINKED ISSUE #13241: Clue plug-in doesn't recognize Twisted Slayer Helmet as a Slayer helm
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Got an elite clue where i have to kill a dust devil and it suggests me to bring a slayer helmet. Wore the twisted slayer helmet but plug-in still showed a red X that it wasn't eligible to use for the clue.

**To Reproduce**
Get a clue step that requires a slayer helmet

**Expected behavior**
Plugin should show a green check mark

**Screenshots**
image

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.0
 - Launcher version: 2.1.5

**Additional context**
None really, should be a small problem

### PR DESCRIPTION
**Pull request by joelewis43**
Closes #13241

Adds the Twisted Slayer Helmet to the list of slayer helmets that satisfy the requirement for the Kill a Dustdevil Skill Clue.

Note: I checked other clues that require the slayer helmet and verified the Twisted Slayer Helmet was already in the list of helms.

### CODE REVIEW

**Comment by makingcomment** [comment]
Isn't it missing the twisted slayer helmet (i) too?

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java [hunk 1]
```diff
@@ -146,7 +146,7 @@
...
+		new SkillChallengeClue("Kill a Dust Devil.", "slay a dust devil.", true, any("Facemask or Slayer Helmet", item(ItemID.FACEMASK), item(ItemID.SLAYER_HELMET), item(ItemID. SLAYER_HELMET_I), item(ItemID. BLACK_SLAYER_HELMET), item(ItemID. BLACK_SLAYER_HELMET_I), item(ItemID. PURPLE_SLAYER_HELMET), item(ItemID. PURPLE_SLAYER_HELMET_I), item(ItemID. RED_SLAYER_HELMET), item(ItemID. RED_SLAYER_HELMET_I), item(ItemID.GREEN_SLAYER_HELMET), item(ItemID. GREEN_SLAYER_HELMET_I), item(ItemID. TURQUOISE_SLAYER_HELMET), item(ItemID. TURQUOISE_SLAYER_HELMET_I), item(ItemID. HYDRA_SLAYER_HELMET), item(ItemID. HYDRA_SLAYER_HELMET_I), item(ItemID.TWISTED_SLAYER_HELMET))),
```
Comment (Hydrox6) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java:149]: You need the imbued helm as well

**Comment by joelewis43** [comment]
Good point. Got that added in too.
