### PR TITLE
npchighlight: fix names showing as null

### LINKED ISSUE #9084: Null NPC at Sulfer Mines
Sulfur Clouds show up as "Null" when using NPC Indicators at the Lovakengj sulfur mining spots.

https://i.imgur.com/huZ5TKx.png

### PR DESCRIPTION
**Pull request by Hermetism**
fix names showing as null in the NPC highlight plugin

fixes #9084

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java [hunk 1]
```diff
@@ -176,11 +176,14 @@ private void renderNpcOverlay(Graphics2D graphics, NPC actor, Color color)
 		if (config.drawNames())
 		{
 			String npcName = Text.removeTags(actor.getName());
-			Point textLocation = actor.getCanvasTextLocation(graphics, npcName, actor.getLogicalHeight() + 40);
-
-			if (textLocation != null)
+			if (npcName != null)
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java]: This should check for actor.getName not being null, before sending it to removeTags

Comment (Hermetism) [reply runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java]: good idea

Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/plugins/npchighlight/NpcSceneOverlay.java]: Any update?
