### PR TITLE
Fix wrong rock respawn timers

### LINKED ISSUE #9442: Adamant Rocks in Wilderness Resource Area Timers not correctly marked as 2x Speed Respawning
**Describe the bug**
The Adamant rocks in the Wilderness Resource Area are, for whatever reason, on a double respawn timer, similar to the rocks in the mining guild. This isn't mentioned on the wiki or any update posts (to my knowledge), and there's no real reason to ever mine there, so it seems to have gone entirely unnoticed, including by the mining respawn timer in RuneLite. All of the other rocks seem to be on a normal respawn timer and are displaying as expected in RuneLite, so I guess this was some sort of oversight on Jagex's end, likely from the release of the mining guild?

https://i.imgur.com/8aB2jc3.png

**To Reproduce**
1. Go to Wilderness Resource Area
2. Mine an Adamant rock with Mining Plugin enabled
3. Wait for rock to respawn

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.29
 - Launcher version: 1.6.0

### PR DESCRIPTION
**Pull request by dekvall**
Fix respawn timers for
 - Adamant rocks in Wilderness Resource area
 - Coal rocks in Miscellania
The doubled respawn rate of the adamant rocks is a possible Jagex bug as
they are the only type of rock within the Wilderness resource area to do so.
The coal rocks in Miscellania are mined for favour instead of ores
and therefore have a shortened respawn time.

Closes #9442, #9452

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java [hunk 1]
```diff
@@ -29,7 +29,36 @@
 import java.util.Map;
 import lombok.AccessLevel;
 import lombok.Getter;
-import static net.runelite.api.ObjectID.*;
+import static net.runelite.api.ObjectID.ASH_PILE;
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/mining/Rock.java]: Since these are static imports, a wildcard import is fine: https://github.com/runelite/runelite/wiki/Code-Conventions#imports

**Comment by dekvall** [comment]
Fixed review commets, thanks!
