### PR TITLE
Clue Scroll: Clarifies Pointed Blue Snelm

### LINKED ISSUE #7618: Medium Emote Clue Blue Snail Helmet
**Describe the bug**
For the Emote Clue helper it tells you that you need a bruised blue snelm, a staff of air and a bronze sq shield. In reality, you need a pointed blue snelm and not a bruised one. Sort of a big deal for iron man who don't have the easiest access to this stuff and can be annoying if you depended on the runelite plug in.

### PR DESCRIPTION
**Pull request by xDemoN**
- Enhanced emote clue overlay to clarify pointed > rounded

Closes #7618

**This is an odd case where any() is being used for 1 item. This is the only way I could think to clarify a pointed blue snelm in the hint overlay.

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java [hunk 1]
```diff
@@ -115,7 +115,7 @@
...
 		new EmoteClue("Headbang at the top of Slayer Tower. Equip a seercull, a combat bracelet and helm of Neitiznot.", OUTSIDE_THE_SLAYER_TOWER_GARGOYLE_ROOM, new WorldPoint(3421, 3537, 2), HEADBANG, item(SEERCULL), range("Combat bracelet", COMBAT_BRACELET4, COMBAT_BRACELET), item(HELM_OF_NEITIZNOT)),
 		new EmoteClue("Dance a jig by the entrance to the Fishing Guild. Equip an emerald ring, a sapphire amulet, and a bronze chain body.", OUTSIDE_THE_FISHING_GUILD, new WorldPoint(2610, 3391, 0), JIG, item(EMERALD_RING), item(SAPPHIRE_AMULET), item(BRONZE_CHAINBODY)),
-		new EmoteClue("Dance a jig under Shantay's Awning. Bow before you talk to me. Equip a pointed blue snail helmet, an air staff and a bronze square shield.", SHANTAY_PASS, new WorldPoint(3304, 3124, 0), JIG, BOW, item(BRUISE_BLUE_SNELM_3343), item(STAFF_OF_AIR), item(BRONZE_SQ_SHIELD)),
+		new EmoteClue("Dance a jig under Shantay's Awning. Bow before you talk to me. Equip a pointed blue snail helmet, an air staff and a bronze square shield.", SHANTAY_PASS, new WorldPoint(3304, 3124, 0), JIG, BOW, any("Bruised Blue Snelm (Pointed)", item(BRUISE_BLUE_SNELM_3343)), item(STAFF_OF_AIR), item(BRONZE_SQ_SHIELD)),
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java]: `"Bruise blue snelm"`

Comment (xDemoN) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java]: The whole point of this was to specify "Pointed" in the hint overlay because jagex uses the same name of "bruised blue snelm" for 2 itemIDs

Comment (Abextm) [reply runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java]: `Bruise` not `Bruised`

**Comment by xDemoN** [comment]
Done

**Comment by xDemoN** [comment]
Requested changes have been addressed. This should be good to go!
