### PR TITLE
Fix clipping in fixed mode for edge snapping map points

### LINKED ISSUE #5618: Clue map markers getting clipped in fixed mode
https://gyazo.com/ee99649ab8ddb060f5207ef21b1fcbaf

https://gyazo.com/efdc018da55d212eb9ced0ff7cf28293

### PR DESCRIPTION
**Pull request by trimbe**
The bounds for the canvas in fixed mode are offset to the right by the size of the border. This translates the canvas bounds back to the left so we don't clip the icon if it's on the left side.

Fixes #5618

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Oh, so it's the black borders when the Runelite client is larger than the fixed mode size that affects this? I see. Will test this and confirm the behavior is correct later today.

File: runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java [hunk 1]
```diff
@@ -92,7 +92,23 @@ public Dimension render(Graphics2D graphics)
 
 		final Rectangle worldMapRectangle = widget.getBounds();
 		final Area mapViewArea = getWorldMapClipArea(worldMapRectangle);
-		final Area canvasViewArea = getWorldMapClipArea(client.getCanvas().getBounds());
+		Area canvasViewArea;
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/ui/overlay/worldmap/WorldMapOverlay.java]: Looks like this can be final? It will only be assigned to once.

**Comment by deathbeam** [comment]
Tbh, wouldn't simply setting X/Y of the canvas bounds unconditionally to 0 here solve the issue as well?
