### PR TITLE
chatfilter: fix colored messages not being collapsed

### LINKED ISSUE #11734: Chat collapse is incompatible with custom chat colors
**Describe the bug**
The new collapse feature of the Chat Filter plugin does not work when custom chat colors are selected using the Chat Color plugin.

**To Reproduce**
1. Go to the config page of the Chat Color plugin
2. Choose different colors for 'Examine' and 'Public chat'
3. Go to the config page of the Chat Filter plugin
4. Tick 'Collapse Game Chat' and 'Collapse Player Chat'
5. Examine an object multiple times, or wait until a player sends the same chat message twice
6. The duplicate messages will not get collapsed.

**Expected behavior**
The duplicate messages should get collapsed, with a message count next to them.

**Screenshots**

After resetting the Chat Color plugin:

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - RuneLite version: 1.6.17
 - Launcher version: 2.1.0

### PR DESCRIPTION
**Pull request by Bardiches**
Chat filter plugin was not collapsing messages that included any formating like colors.

Fixes #11734

### CODE REVIEW

File: runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java [hunk 1]
```diff
@@ -382,4 +382,16 @@ public void publicChatFilteredOnDuplicate()
 
 		assertEquals(0, client.getIntStack()[client.getIntStackSize() - 3]);
 	}
+
+	@Test
+	public void testDuplicateChatFilterIgnoresColor()
```
Comment (Adam-) [inline runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java:387]: This test appears unrelated to the issue, and also passes on master without any modifications to the plugin.

Comment (Bardiches) [reply runelite-client/src/test/java/net/runelite/client/plugins/chatfilter/ChatFilterPluginTest.java:387]: My bad, published the wrong version.

File: runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java [hunk 2]
```diff
@@ -192,7 +192,7 @@ public void onScriptCallbackEvent(ScriptCallbackEvent event)
 			: COLLAPSIBLE_MESSAGETYPES.contains(chatMessageType) && config.collapseGameChat();
 		if (!blockMessage && shouldCollapse)
 		{
-			Duplicate duplicateCacheEntry = duplicateChatCache.get(name + ":" + message);
+			Duplicate duplicateCacheEntry = duplicateChatCache.get(name + ":" + messageNode.getValue());
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java:195]: Are you sure this is correct? I think `message` always has to be `messageNode.getValue()`?

File: runelite-client/src/main/java/net/runelite/client/plugins/emojis/EmojiPlugin.java [hunk 3]
```diff
@@ -201,29 +201,4 @@ String updateMessage(final String message)
 
 		return Strings.join(messageWords, " ");
 	}
-
-	/**
-	 * Remove tags, except for &lt;lt&gt; and &lt;gt&gt;
-	 *
-	 * @return
-	 */
-	private static String removeTags(String str)
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/emojis/EmojiPlugin.java:210]: Moving `removeFormattingTags` is fine, but should be in a separate commit since it is unrelated.

File: runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java (hunk 2 above)
Comment (Bardiches) [reply runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java]: Good callout, they're the same, so I changed back to using just `message`.

File: runelite-client/src/main/java/net/runelite/client/plugins/emojis/EmojiPlugin.java (hunk 3 above)
Comment (Bardiches) [reply runelite-client/src/main/java/net/runelite/client/plugins/emojis/EmojiPlugin.java]: Sure, removed.
