### PR TITLE
TimeTracking: Add farming notifications

### LINKED ISSUE #2212: Notifications to Farming Tracker
Since we now have a Farming Tracker in 1.3.7, maybe we can have chat messages notifying of crops ready for harvest on login/whenever they get ready whilst logged in? OSB had these but they were broken, and only when you were near the crop.

### PR DESCRIPTION
**Pull request by loldudester**
Closes #2212

This adds configurable notifications to each farming patch.

https://user-images.githubusercontent.com/7504779/104942380-4877f480-59ac-11eb-9f2e-6382b35926fd.mp4

It notifies across profile types and accounts, with an indicator if the notification is for a different profile or account to the current one.

The swing stuff is likely hot garbage as I haven't really used it before _but it works_..

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java [hunk 1]
```diff
@@ -255,15 +259,16 @@ private void onWidgetClosed(WidgetClosed ev)
 		}
 	}
 
-	@Schedule(period = 10, unit = ChronoUnit.SECONDS)
-	public void checkCompletion()
+	private void checkCompletion()
 	{
 		boolean birdHouseDataChanged = birdHouseTracker.checkCompletion();
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java:264]: N.B. this call is moving threads.

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTabPanel.java [hunk 2]
```diff
@@ -209,6 +240,30 @@ public void update()
...
 			}
+
+			String configKey = NOTIFY_CONFIG_KEY +
+				"." + patch.getRegion().getRegionID() +
+				"." + patch.getVarbit().getId();
+
+			JButton toggleNotify = panel.getNotifyIcon();
+
+
+			ImageIcon notifyIcon = new ImageIcon(ImageUtil.resizeImage(itemManager.getImage(ItemID.BELL_BAUBLE_6847), 18, 16));
```
Comment (abextm) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTabPanel.java:251]: probably should use a greyscale icon from fontawesome or somewhere.
https://fontawesome.com/icons/bell?style=solid and https://fontawesome.com/icons/bell-slash?style=regular

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java [hunk 3]
```diff
@@ -29,30 +29,40 @@
...
 import net.runelite.api.vars.Autoweed;
 import net.runelite.api.widgets.WidgetModalMode;
+import net.runelite.client.Notifier;
 import net.runelite.client.config.ConfigManager;
+import net.runelite.client.config.RuneScapeProfile;
+import net.runelite.client.config.RuneScapeProfileType;
 import net.runelite.client.game.ItemManager;
 import net.runelite.client.plugins.timetracking.SummaryState;
 import net.runelite.client.plugins.timetracking.Tab;
+import static net.runelite.client.plugins.timetracking.TabContentPanel.getFormattedEstimate;
```
Comment (abextm) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java:50]: don't static import

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java [hunk 4]
```diff
@@ -29,30 +29,40 @@
...
 import net.runelite.client.plugins.timetracking.TimeTrackingConfig;
+import net.runelite.client.util.Text;
 
 @Slf4j
 @Singleton
 public class FarmingTracker
 {
+	private static final String NOTIFY_CONFIG_KEY = "notify";
```
Comment (abextm) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java:58]: config

**Review by abextm — CHANGES_REQUESTED** [review]

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java [hunk 5]
```diff
@@ -457,4 +474,112 @@ else if (maxCompletionTime <= Instant.now().getEpochSecond())
...
+			Integer offsetPrecisionMins = configManager.getConfiguration(TimeTrackingConfig.CONFIG_GROUP, profile.getKey(), TimeTrackingConfig.FARM_TICK_OFFSET_PRECISION, int.class);
+			Integer offsetTimeMins = configManager.getConfiguration(TimeTrackingConfig.CONFIG_GROUP, profile.getKey(), TimeTrackingConfig.FARM_TICK_OFFSET, int.class);
+
+			RuneScapeProfileType profileType = profile.getType();
+
+			for (Map.Entry<Tab, Set<FarmingPatch>> tab : farmingWorld.getTabs().entrySet())
+			{
+				for (FarmingPatch patch : tab.getValue())
+				{
+					String configKey = NOTIFY_CONFIG_KEY +
```
[the remark this answers is not in the document]
Comment (loldudester) [reply runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java:494]: Would it make sense to have the patch method give just the `<regionID>.<varbitID>` as that's used in more places, and still prepend the `NOTIFY` string in the tracker+panel?

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java [hunk 6]
```diff
@@ -457,4 +474,112 @@ else if (maxCompletionTime <= Instant.now().getEpochSecond())
...
+					{
+						PatchPrediction prediction = predictPatch(patch, profile.getKey());
+						if (prediction != null)
+						{
+							int tickRate = prediction.getProduce().getTickrate();
+
+							//Only notify if recorded offset is large enough for the current patch
+							if (offsetPrecisionMins != null && offsetTimeMins != null && (offsetPrecisionMins >= tickRate || offsetPrecisionMins >= 40))
+							{
+								if ((unixNow - 10 <= prediction.getDoneEstimate() && prediction.getDoneEstimate() <= unixNow) && prediction.getProduce() != Produce.WEEDS)
```
[the remark this answers is not in the document]
Comment (loldudester) [reply runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java:510]: My only other thought was for each time the method is fired record the Unix time and compare to that instead of `unixNow-10`.

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (abextm) [reply runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java]: probably one with notify and one without

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (abextm) [reply runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java]: what you need to avoid is:
1) the scheduler being blocked for a long period of time, and thus not calling this exactly on the right time, should not drop notifications
2) Instant.now() is not monotonic, so time moving backwards (or forwards) should not drop/duplicate notifications

Probably the most reliable thing would be to record the state of the crops as of the previous check and only fire notifications if the state has changed

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeablePanel.java [hunk 7]
```diff
@@ -79,8 +86,29 @@ public TimeablePanel(T timeable, String title, int maximumProgressValue)
...
+
+		notifyButton.setPreferredSize(new Dimension(30, 16));
+		notifyButton.setBorder(new EmptyBorder(0, 0, 0, 10));
+		notifyButton.setIcon(notifyIcon);
+		notifyButton.setSelectedIcon(notifySelectedIcon);
+		SwingUtil.removeButtonDecorations(notifyButton);
+
+		JPanel notifyPanel = new JPanel();
+		notifyPanel.setLayout(new BorderLayout());
+		notifyPanel.setBorder(new EmptyBorder(0, 0, 0, 0));
```
[the remark this answers is not in the document]
Comment (loldudester) [reply runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeablePanel.java:100]: Sure is

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (loldudester) [reply runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java]: I'm not sure how to do this as while predictPatch returns a CropState, it's just the initial CropState of the varbit it reads from the config (ie the last observed state), so we'd still need some method at some point to compare predictPatch's `doneEstimate` with the current time to update the CropState to `HARVESTABLE`

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java [hunk 8]
```diff
@@ -27,22 +27,31 @@
...
+import net.runelite.client.Notifier;
 import net.runelite.client.config.ConfigManager;
+import net.runelite.client.config.RuneScapeProfile;
+import net.runelite.client.config.RuneScapeProfileType;
 import net.runelite.client.game.ItemManager;
 import net.runelite.client.plugins.timetracking.SummaryState;
 import net.runelite.client.plugins.timetracking.Tab;
 import net.runelite.client.plugins.timetracking.TimeTrackingConfig;
+import net.runelite.client.util.Text;
+
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java:54]: Remove this extra newline
```suggestion
```

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/ProfilePatch.java [hunk 9]
```diff
@@ -0,0 +1,10 @@
+package net.runelite.client.plugins.timetracking.farming;
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/ProfilePatch.java:1]: Copyright header

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java [hunk 10]
```diff
@@ -189,11 +200,16 @@ else if (!newRegionLoaded && timeSinceModalClose > 1)
...
+							if (currentPatchState.getTickRate() != 0)
+							{
+								wasNotified.put(new ProfilePatch(patch, configManager.getRSProfileKey()), false);
+							}
 						}
 						else
 						{
 							log.debug("ignoring growth tick for offset calculation; newRegionLoaded={} timeSinceModalClose={}", newRegionLoaded, timeSinceModalClose);
 						}
+
```
Comment (abextm) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java:212]:
```suggestion
```

**Review by abextm — COMMENTED** [review]
can you squash this?

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java [hunk 11]
```diff
@@ -505,99 +509,72 @@ public void checkCompletion()
 
 					int tickRate = prediction.getProduce().getTickrate();
 					
-					if (offsetPrecisionMins == null || offsetTimeMins == null || (offsetPrecisionMins < tickRate && offsetPrecisionMins < 40) || prediction.getProduce() == Produce.WEEDS)
+					if (offsetPrecisionMins == null || offsetTimeMins == null || (offsetPrecisionMins < tickRate && offsetPrecisionMins < 40) || prediction.getProduce() == Produce.WEEDS
```
Comment (abextm) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java:512]: as this is it won't notify if you watch the crop grow because it switches to a non-ticking state. It should give the notification while watching it too.

Comment (loldudester) [reply runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java:512]: It's using `Produce::tickrate`, which just provides the regular tick rate, as opposed to `PatchState::getTickRate` which is based on the current CropState

Comment (abextm) [reply runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java:511]: the predictor uses PatchState's tickrate, so the done estimate will always be zero if its observed it done.

**Comment by loldudester** [comment]
I think this is about right now, after fixing some edge cases like check-health checks and regrowth.

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java [hunk 12]
```diff
@@ -58,7 +58,6 @@
 import net.runelite.client.plugins.timetracking.farming.FarmingContractManager;
 import net.runelite.client.plugins.timetracking.farming.FarmingTracker;
 import net.runelite.client.plugins.timetracking.hunter.BirdHouseTracker;
-import net.runelite.client.task.Schedule;
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java:61]: This should be part of the first commit

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java [hunk 13]
```diff
@@ -29,10 +29,10 @@
 import com.google.inject.Provides;
 import java.awt.image.BufferedImage;
 import java.time.Instant;
-import java.time.temporal.ChronoUnit;
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java:32]: As should this

File: runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java [hunk 14]
```diff
@@ -68,6 +66,8 @@
 	description = "Enable the Time Tracking panel, which contains timers, stopwatches, and farming and bird house trackers",
 	tags = {"birdhouse", "farming", "hunter", "notifications", "skilling", "stopwatches", "timers", "panel"}
 )
+
```
[the remark this answers is not in the document]
Comment (abextm) [reply runelite-client/src/main/java/net/runelite/client/plugins/timetracking/TimeTrackingPlugin.java:70]: still here

**Review by abextm — APPROVED** [review]

**Comment by Joshwat** [comment]
Would be possible to add a in-game chat notification (toggleable, similar to staves, buckets, etc) and a flash color selection to this feature? Currently it is hard to tell if you're being notificated for AFK'ing (for example) or because your crops grown
