### PR TITLE
Idle Notifier: Add ent chopping

### LINKED ISSUE #12898: Ent idle notifier
**Describe the bug**
The idle notifier doesn't notify when done chopping an ent trunk

**To Reproduce**
Kill an ent and chop it's trunk while the idle notifier plugin is on

**Expected behavior**
Notify when done chopping

**Environment (please complete the following information):**
 - OS: Ubuntu (pretty sure it happens on Windows as well)
 - RuneLite version: 1.6.33
 - Launcher version: 2.1.3

I also noticed that the loot tracker plugin doesn't work for ent trunks, is this intended?

### PR DESCRIPTION
**Pull request by BBeeaarr**
Add ent chopping to idle notification plugin
Add ent chopping IDs
Closes #12898
Updated Version of #17028 to include 2H axes

### CODE REVIEW

File: runelite-api/src/main/java/net/runelite/api/AnimationID.java [hunk 1]
```diff
@@ -59,6 +59,31 @@ public final class AnimationID
...
 	public static final int WOODCUTTING_2H_3A = 10074;
+	/*Ent animation shared with Canoe cutting*/
+	public static final int WOODCUTTING_ENT_BRONZE = 3291;
+	public static final int WOODCUTTING_ENT_IRON = 3290;
+	public static final int WOODCUTTING_ENT_STEEL = 3289;
+	public static final int WOODCUTTING_ENT_BLACK = 3288;
+	public static final int WOODCUTTING_ENT_MITHRIL = 3287;
+	public static final int WOODCUTTING_ENT_ADAMANT = 3286;
+	public static final int WOODCUTTING_ENT_RUNE = 3285;
+	public static final int WOODCUTTING_ENT_DRAGON = 3292;
```
Comment (Nightfirecat) [inline runelite-api/src/main/java/net/runelite/api/AnimationID.java:70]: `WOODCUTTING_ENT_DRAGON_OR` is missing; from testing with dev tools, it appears to be `23`--it would be helpful to have this confirmed though.

Comment (Nightfirecat) [reply runelite-api/src/main/java/net/runelite/api/AnimationID.java:70]: I'm not sure what `WOODCUTTING_ENT_INFERNAL` is offhand, I can test later with a real infernal axe if needed.

File: runelite-api/src/main/java/net/runelite/api/AnimationID.java [hunk 2]
```diff
@@ -59,6 +59,31 @@ public final class AnimationID
...
+	public static final int WOODCUTTING_ENT_CRYSTAL = 8327;
```
Comment (Nightfirecat) [inline runelite-api/src/main/java/net/runelite/api/AnimationID.java:71]: Do you have a crystal axe to confirm which one is active versus inactive, or is this a guess? Visually, I think this is backwards, as 8327 is closer to white (which would match the look of the inactive axe) while 8323 is more blue.

File: runelite-api/src/main/java/net/runelite/api/AnimationID.java [hunk 3]
```diff
@@ -59,6 +59,31 @@ public final class AnimationID
...
+	public static final int WOODCUTTING_ENT_CRYSTAL_INACTIVE = 8323;
+	public static final int WOODCUTTING_ENT_GILDED = 8305;
+	public static final int WOODCUTTING_ENT_3A = 7266;
+	public static final int WOODCUTTING_ENT_INFERNAL = 8780;
```
Comment (Nightfirecat) [inline runelite-api/src/main/java/net/runelite/api/AnimationID.java:75]: This looks like the trailblazer axe (and possibly infernal axe (or), if ent woodcutting anims are similar to regular tree anims), not the infernal axe.

File: runelite-api/src/main/java/net/runelite/api/AnimationID.java [hunk 4]
```diff
@@ -59,6 +59,31 @@ public final class AnimationID
...
+	public static final int WOODCUTTING_ENT_2H_BRONZE = 10517;
+	public static final int WOODCUTTING_ENT_2H_IRON = 10518;
+	public static final int WOODCUTTING_ENT_2H_STEEL = 10519;
+	public static final int WOODCUTTING_ENT_2H_BLACK = 10520;
+	public static final int WOODCUTTING_ENT_2H_MITHRIL = 10521;
+	public static final int WOODCUTTING_ENT_2H_ADAMANT = 10522;
+	public static final int WOODCUTTING_ENT_2H_RUNE = 10523;
+	public static final int WOODCUTTING_ENT_2H_DRAGON = 10524;
+	public static final int WOODCUTTING_ENT_2H_CRYSTAL = 10526;
```
Comment (Nightfirecat) [inline runelite-api/src/main/java/net/runelite/api/AnimationID.java:84]: This seems to be backwards; 10525 is the active crystal axe, 10526 is the inactive axe.

File: runelite-api/src/main/java/net/runelite/api/AnimationID.java (hunk 2 above)
Comment (capslock13) [reply runelite-api/src/main/java/net/runelite/api/AnimationID.java:71]: I can confirm crystal is 8323 instead of 8327

File: runelite-api/src/main/java/net/runelite/api/AnimationID.java (hunk 3 above)
Comment (capslock13) [reply runelite-api/src/main/java/net/runelite/api/AnimationID.java:75]: Infernal axe seems to be 2116

File: runelite-api/src/main/java/net/runelite/api/AnimationID.java (hunk 1 above)
Comment (capslock13) [reply runelite-api/src/main/java/net/runelite/api/AnimationID.java:70]: Dragon Axe (or) is 23
