### PR TITLE
Fix Nightmare Zone Overload timer and notification

### LINKED ISSUE #12493: Nightmare Zone overload timer and notification are not cleared when leaving
The overload infobox timer is not cleared when leaving the instance. Additionally, the overload expiry notification can trigger immediately upon re-entering NMZ which also should not happen. Both of these features should have their times reset or cleared when leaving the NMZ instance

### PR DESCRIPTION
**Pull request by spatiag**
Close #12493 

The timers plugin was not checking to see if the player was still inside NMZ, causing the timer to stay when the player left or hopped worlds. Now checks to see if the player is inside the NMZ region.

For the nightmarezone plugin, `overloadNotificationSend = true` when the player drinks an Overload potion. When the player leaves NMZ before the Overload expires and re-enters, `overloadNotificationSend` is still `true`. This results in the notification still being sent based on when the potion was drunk in the previous NMZ instance. Now sets `overloadNotificationSend` to `false` upon leaving.

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java [hunk 1]
```diff
@@ -708,6 +712,11 @@ private boolean isInInferno()
 		return client.getMapRegions() != null && ArrayUtils.contains(client.getMapRegions(), INFERNO_REGION_ID);
 	}
 
+	private boolean isInNightmareZone()
+	{
+		return client.getMapRegions() != null && ArrayUtils.contains(client.getMapRegions(), NMZ_MAP_REGION_ID);
+	}
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java:718]: This should use the same logic as is used in the nightmare zone plugin. I don't think it's an important distinction in this particular case, but this would give false positive results when in KBD's lair

File: runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java [hunk 2]
```diff
@@ -143,6 +144,7 @@
 	private int lastAnimation;
 	private boolean loggedInRace;
 	private boolean widgetHiddenChangedOnPvpWorld;
+	private boolean overloadNMZ;
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java:147]: What purpose does this serve? We can safely call `removeGameTimer(OVERLOAD)` even if the timer hasn't been added.

File: runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java [hunk 3]
```diff
@@ -135,6 +135,11 @@ public void onGameTick(GameTick event)
 				resetPointsPerHour();
 			}
 
+			if (overloadNotificationSend)
+			{
+				overloadNotificationSend = false;
+			}
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java:141]:
```suggestion
			overloadNotificationSend = false;
```

**Review by Nightfirecat — CHANGES_REQUESTED** [review]

File: runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java (hunk 1 above)
Comment (spatiag) [reply runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java:718]: Sorry, I forgot about NMZ and KBD using the same region. Fixed in a new commit.

File: runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java (hunk 2 above)
Comment (spatiag) [reply runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java:147]: I added `overloadNMZ` to mimic how the `tzhaarTimer` is used and to also limit the number of calls to `removeGameTimer(OVERLOAD)`. I originally had this 
```
if (!isInNightmareZone())
{
	removeGameTimer(OVERLOAD);
}
```
but it gets triggered frequently outside NMZ by just walking around and loading in new regions.

File: runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java (hunk 3 above)
Comment (spatiag) [reply runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java:141]: I was thinking of doing it this way, but decided to imitate how `absorptionNotificationSend` is handled. 
```
if (!absorptionNotificationSend)
{
	absorptionNotificationSend = true;
}
```

Should we change that block of code to just `absorptionNotificationSend = true` along with `overloadNotificationSend = false`?

File: runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java (hunk 2 above)
Comment (Nightfirecat) [reply runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java:147]: Is it bad for it to be called when walking around? I don't think that's an issue.

File: runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java (hunk 3 above)
Comment (Nightfirecat) [reply runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java:141]: I'm not really sure why it was written as it is, but leave it be. This, however, should not be written the same way since it makes no sense.

File: runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java [hunk 4]
```diff
@@ -800,6 +823,7 @@ public void onGameStateChanged(GameStateChanged gameStateChanged)
 
 				removeTzhaarTimer(); // will be readded by the wave message
 				removeGameTimer(TELEBLOCK);
+				removeNMZOverloadTimer();
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java:826]: The timer removal only has to be in LOADING I think.

File: runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java (hunk 3 above)
Comment (Adam-) [reply runelite-client/src/main/java/net/runelite/client/plugins/nightmarezone/NightmareZonePlugin.java:141]: I've also noticed `absorptionNotificationSend = true` is missing from startUp()
