### PR TITLE
Cannon: fix reclaimed cannon initial cball counter

### LINKED ISSUE #13105: Cannon plugin not tracking cannonballs correctly after being destroyed and reclaimed
**Description**
I brought my cannon to KBD with the 'cannon' plugin enabled. The settings for my plugin showed how many cannonballs were remaining and the double-hit spots. After some time, KBD destroyed my cannon when there was 7 cannonballs left in it. Although my cannon was destroyed, the cannon overlay remained where it was. May it also be noted that after I reclaimed my cannon and tried to use it again... 7 cannonballs were what the plugin considered to be the max (actually 30 in game). After filling my cannon with cannonballs again, the overlay displayed that there were 7 cannonballs loaded and starting counting down to -23.

**To Reproduce**
1. Go to KBD with the cannon plugin enabled and the overlay on.
2. Fill your cannon and let it begin to fire cannonballs
3. Wait for KBD to destroy your cannon (overlay remains Error)
4. Reclaim your cannon and try placing it down and letting it fire (see Error).

**Expected behavior**
It would be expected that the cannon overlay would disappear after it was destroyed and perhaps an overlay message in the game window saying "Your cannon has been destroyed. See Nulodion in-game to reclaim it."

**Screenshots**
No Screenshots. Sorry :{

**Environment:**
 - OS: Windows 10 Home x64 Version 10.0.18363
 - RuneLite version: 1.6.36.2

### PR DESCRIPTION
**Pull request by Alexsuperfly**
A cannon that has been destroyed with cannon balls loaded
will still have them loaded when reclaimed.  This commit
does a diff of the inventory on the first message that says 
you are loading the cannon.  If the diff and inventory 
after that message both have cannon balls in them, then
we know the maximum amount possible were stored so set 
the counter to max.

Fixes #13105

### CODE REVIEW

**Review by Nightfirecat — COMMENTED** [review]
Has been mentioned that this should do an inventory diff to find out how many balls have been loaded.

**Review by Nightfirecat — CHANGES_REQUESTED** [review]
Also the first and second commits can be squashed? The third commit should remain separate.

File: runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java [hunk 1]
```diff
@@ -198,6 +206,26 @@ public void onItemContainerChanged(ItemContainerChanged event)
...
+		if (inventorySnapshot != null)
+		{
+			Multiset<Integer> diff = generateInventoryDiff();
+			int snapshotCannonballs = inventorySnapshot.count(ItemID.CANNONBALL);
+			int diffCannonballs = diff.count(ItemID.CANNONBALL);
+			int snapshotGraniteCannonballs = inventorySnapshot.count(ItemID.GRANITE_CANNONBALL);
+			int diffGraniteCannonballs = diff.count(ItemID.GRANITE_CANNONBALL);
+
+			if ((diffCannonballs > 0 && snapshotCannonballs > diffCannonballs)
+					|| (diffGraniteCannonballs > 0 && snapshotGraniteCannonballs > diffGraniteCannonballs))
```
[the remark this answers is not in the document]
Comment (Alexsuperfly) [reply runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java:221]: good shout, i think this can actually just become `diff.contains(ItemID.CANNONBALL) && inventory.contains(ItemID.CANNONBALL)` then, since all that matters is the diff and current inventory both contain cannonballs in them

**Comment by Nightfirecat** [comment]
Do you know offhand what test cases you were testing ingame to make sure these changes worked? I'd like to add tests to this.

**Comment by Nightfirecat** [comment]
I've added a test for your second commit. I'm happy to write a test for your first commit as well (and maybe the rest of the plugin while I'm at it) if you can share the steps you took to test this ingame

File: runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java [hunk 2]
```diff
@@ -24,9 +24,14 @@
  */
 package net.runelite.client.plugins.cannon;
 
+import com.google.common.annotations.VisibleForTesting;
```
Comment (Cyborger1) [inline runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java:27]: It appears this line is causing a CheckStyle violation. Did you intend to add this annotation somewhere?

**Comment by Alexsuperfly** [comment]
> I've added a test for your second commit. I'm happy to write a test for your first commit as well (and maybe the rest of the plugin while I'm at it) if you can share the steps you took to test this ingame

The process to test each case would be:

- place the cannon in KQs lair
- load with cannonballs and start firing
- KQ destroys the cannon
- reclaim the cannon from Nulodion
- setup the cannon in barb village (dwarfs dont let you place it next to them)

each test case is:

1. load regular, set back up with excess regular in invent, observe cannon reading 30
2. 1 but with granite cannonballs
3. load regular, set back up with <= amount of space in cannon of balls in invent, observe only the loaded amount displayed (this is a case i dont believe can be solved since the client can be shut down between destruction and claim, so theres no way to preserve the known number of cannonballs in the cannon)
4. 3 but with granite cannonballs
5. load regular, set back up with any amount of granite cannonballs in invent, observe the "you cant mix cannonballs message" and the count is set correctly to the message that displays how many balls are loaded
6. load granite, set back up with only regular in invent, same as 5

**Comment by Nightfirecat** [comment]
Ok, I've added tests which cover the added functionality in your commits. I've also added a commit to remember the previous cannonball count when it is destroyed and later set up. I think this is probably all set now?

File: runelite-client/src/test/java/net/runelite/client/plugins/cannon/CannonPluginTest.java [hunk 3]
```diff
@@ -204,6 +204,7 @@ public void cannonDestroyedSetupNormalCannonballs()
 		assertEquals(30, plugin.getCballsLeft());
```
Comment (Alexsuperfly) [inline runelite-client/src/test/java/net/runelite/client/plugins/cannon/CannonPluginTest.java:204]: after this commit these arnt really testing the inventory diff system since the message will add 5 and 25 to equal 30 regardless of what the inventory diff decides the contents are

**Comment by Nightfirecat** [comment]
Your point on the tests is taken. I've incorporated your recommended changes (along with some further changes on my part to fix up these commits) and I think it's all set now.

File: runelite-client/src/test/java/net/runelite/client/plugins/cannon/CannonPluginTest.java [hunk 4]
```diff
@@ -171,6 +179,145 @@ public void unloadCannon()
...
+		final ItemContainer inventory = mock(ItemContainer.class);
+		final Item[] inventoryContentsBefore = { new Item(ItemID.CANNONBALL, 100), new Item(ItemID.GRANITE_CANNONBALL, 100) };
+		when(inventory.getItems()).thenReturn(inventoryContentsBefore);
+		when(inventory.contains(ItemID.CANNONBALL)).thenReturn(true);
+		lenient().when(inventory.contains(ItemID.GRANITE_CANNONBALL)).thenReturn(true);
+		when(client.getItemContainer(InventoryID.INVENTORY)).thenReturn(inventory);
+
+		plugin.onChatMessage(loadCannonballs(25));
+
+		final Item[] inventoryContentsAfter = { new Item(ItemID.CANNONBALL, 75), new Item(ItemID.GRANITE_CANNONBALL, 100) };
```
Comment (Alexsuperfly) [inline runelite-client/src/test/java/net/runelite/client/plugins/cannon/CannonPluginTest.java:220]: This doesn't really follow in game behavior since it will always load granite cannonballs if they exist in your inventory, no matter what, but for the purposes of testing code paths this could be fine.

File: runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java [hunk 5]
```diff
@@ -300,15 +327,20 @@ public void onChatMessage(ChatMessage event)
 		{
 			cannonPlaced = true;
 			addCounter();
+			justPlaced = true;
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java:330]: From testing in game, it seems like it's not possible to add the furnace but also not load it if you have cballs in your inventory. So I think you could just check if there are >= 30 cballs here and if so set the cballs left to 30 then. Then you could avoid the whole inv snapshot thing. That would fix most of the scenarios except if you had a partially-filled broken cannon and also <30 cannon balls to re-load it when replacing.

File: runelite-client/src/test/java/net/runelite/client/plugins/cannon/CannonPluginTest.java [hunk 6]
```diff
@@ -0,0 +1,172 @@
...
+	@Bind
+	private Client client;
+
+	@Mock
+	@Bind
+	private OverlayManager overlayManager;
+
+	private static final ChatMessage ADD_FURNACE = new ChatMessage();
+
+	static
```
Comment (Adam-) [inline runelite-client/src/test/java/net/runelite/client/plugins/cannon/CannonPluginTest.java:93]: Prefer `@BeforeClass` - since if this fails it will hard fail the test runner.

File: runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java [hunk 7]
```diff
@@ -301,6 +302,23 @@ public void onChatMessage(ChatMessage event)
 			cannonPlaced = true;
 			addCounter();
 			cballsLeft = 0;
+
+			final ItemContainer inventory = client.getItemContainer(InventoryID.INVENTORY);
+			if (inventory != null)
+			{
+				int invCballs = inventory.count(ItemID.GRANITE_CANNONBALL) > 0
+						? inventory.count(ItemID.GRANITE_CANNONBALL)
+						: inventory.count(ItemID.CANNONBALL);
```
Comment (maxbla) [inline runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java:311]: I think this logic causes a bug if the player's cannon is destroyed when containing normal cannonballs, then they bring 30+ granite cannonballs and no normal cannonballs the next time they place it. I can't test it because I don't have any granite cannonballs right now.

Comment (Alexsuperfly) [reply runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java:311]: I dont see how 5bfbff492d4bff1f40aeb3cd411f6766b6a6ba67 doesn't address that.

Comment (maxbla) [reply runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonPlugin.java:311]: 5bfbff4 does address that. Sorry for the mistake.
