### PR TITLE
Nmz Plugin - Fix area check to exclude KBD lair

### LINKED ISSUE #3692: NMZ overlay active in KBD private instance
KBD lair is the same region as NMZ, so the points overlay is showing up

[https://gyazo.com/512afc360389590644b75a198f6b0215](https://gyazo.com/512afc360389590644b75a198f6b0215)

### PR DESCRIPTION
**Pull request by TheStonedTurtle**
Fixes #3692

### CODE REVIEW

**Comment by Nightfirecat** [comment]
We should also update the Discord plugin to recognize the difference as it currently thinks players in KBD's lair are in Nightmare Zone.

File: runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java [hunk 1]
```diff
@@ -87,6 +87,8 @@
 	BOSS_ZALCANO("Zalcano", DiscordAreaType.BOSSES, 13250),
 	BOSS_ZULRAH("Zulrah", DiscordAreaType.BOSSES, 9007),
 	BOSS_NIGHTMARE("Nightmare of Ashihama", DiscordAreaType.BOSSES, 15515),
+	// KBD shares its region with NMZ and should be manually checked for and assigned by the plugin
+	BOSS_KING_BLACK_DRAGON("King black dragon", DiscordAreaType.BOSSES),
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordGameEventType.java]: Given that we don't show players as being in the wilderness and players necessarily must travel through the wilderness to get to KBD, I think we shouldn't show this at all.

File: runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java [hunk 2]
```diff
@@ -381,7 +381,14 @@ private void checkForAreaUpdate()
 			return;
 		}
 
-		final DiscordGameEventType discordGameEventType = DiscordGameEventType.fromRegion(playerRegionID);
+		DiscordGameEventType discordGameEventType = DiscordGameEventType.fromRegion(playerRegionID);
```
Comment (Nightfirecat) [inline runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java]: Add a newline after this so it doesn't look like one big block.
```suggestion
		DiscordGameEventType discordGameEventType = DiscordGameEventType.fromRegion(playerRegionID);

```
