### PR TITLE
ImageUtil: add error log with path

### LINKED ISSUE #10708: ImageUtil.getResourceStreamFromClass does not log attempted path if load fails
As it currently stands, the method will (after a lengthy set of stacktraces) yield the following exceptions:

```
Caused by: java.lang.IllegalArgumentException: file.png
 
Caused by: java.lang.IllegalArgumentException: input == null!
```

It would be helpful to developers to print the searched path so they can more easily figure out why their images are not being loaded.

### PR DESCRIPTION
**Pull request by kkozera**
Close #10708

I came with this idea to show exact place where file should be.

Is there any better way to handle it?

### CODE REVIEW

File: runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java [hunk 1]
```diff
@@ -351,6 +351,16 @@ public static BufferedImage getResourceStreamFromClass(final Class c, final Stri
 		}
 		catch (IllegalArgumentException e)
 		{
+			if (path.startsWith("/"))
```
Comment (deathbeam) [inline runelite-client/src/main/java/net/runelite/client/util/ImageUtil.java:354]: Just store the path and then call log.warn only once

**Review by deathbeam — CHANGES_REQUESTED** [review]

**Review by deathbeam — APPROVED** [review]
