### PR TITLE
runelite-client: Handle startup with an empty cache better

### LINKED ISSUE #7600: NPE is SpriteManager#getSprite on clan icon manager startup and on screenshot
```
2019-01-28 11:46:14 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 11:46:16 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 11:46:19 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,247,117,809x534,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@bfd2cb1,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 11:46:19 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 11:46:22 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 11478ms. Uptime: 25311ms
2019-01-28 11:46:33 [Thread-7] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.SpriteManager.lambda$getSpriteAsync$0(SpriteManager.java:92)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:156)
	at client.methodDraw(client.java:1265)
	at client.ar(client.java)
	at ah.o(ah.java:356)
	at ah.run(ah.java:310)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:47:10 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.ClanManager.loadClanChatIcons(ClanManager.java:155)
	at net.runelite.client.game.ClanManager.onGameStateChanged(ClanManager.java:136)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:47:10 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.plugins.screenshot.ScreenshotPlugin.onGameStateChanged(ScreenshotPlugin.java:254)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:52:24 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.ClanManager.loadClanChatIcons(ClanManager.java:155)
	at net.runelite.client.game.ClanManager.onGameStateChanged(ClanManager.java:136)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:52:41 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.ClanManager.loadClanChatIcons(ClanManager.java:155)
	at net.runelite.client.game.ClanManager.onGameStateChanged(ClanManager.java:136)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:54:56 [Thread-7] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.client.game.SpriteManager.getSprite(SpriteManager.java:75)
	at net.runelite.client.game.ClanManager.loadClanChatIcons(ClanManager.java:155)
	at net.runelite.client.game.ClanManager.onGameStateChanged(ClanManager.java:136)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:130)
	at client.gameStateChanged(client.java:933)
	at h.ek(h.java:1700)
	at client.ae(client.java:1527)
	at ah.u(ah.java:330)
	at ah.run(ah.java:309)
	at java.lang.Thread.run(Thread.java:748)
2019-01-28 11:57:33 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 11:57:34 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 11:57:37 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@5329c08a,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 11:57:37 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 11:57:40 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 11234ms. Uptime: 13644ms
2019-01-28 12:04:51 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:04:56 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:05:00 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@3ff542bb,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:05:00 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:05:09 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 26347ms. Uptime: 33279ms
2019-01-28 12:08:17 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:08:19 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:08:23 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@41296f53,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:08:23 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:08:28 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 17285ms. Uptime: 21014ms
2019-01-28 12:13:43 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:13:46 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:13:48 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@c940673,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:13:48 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:13:52 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 13075ms. Uptime: 15875ms
2019-01-28 12:33:21 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:33:24 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:33:26 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@228ea513,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:33:26 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:33:30 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 13519ms. Uptime: 16023ms
2019-01-28 12:35:59 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:35:59 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:36:03 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@5f7f2d1a,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:36:03 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:36:09 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 14316ms. Uptime: 16681ms
2019-01-28 12:37:58 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:37:59 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:38:01 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@18b80c94,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:38:01 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:38:05 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 11381ms. Uptime: 13683ms
2019-01-28 12:42:33 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-01-28 12:42:36 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-01-28 12:42:38 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1303x768,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@6cc74f99,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-01-28 12:42:38 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-01-28 12:42:41 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 13528ms. Uptime: 16050ms
```

### PR DESCRIPTION
**Pull request by abextm**
Closes #7600

### CODE REVIEW

**Comment by Adam-** [comment]
`Client.getSprites()` should maybe be marked nullable due to this too.

File: runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java [hunk 1]
```diff
@@ -71,6 +72,14 @@ public void addInfoBox(InfoBox infoBox)
 		updateInfoBoxImage(infoBox);
 		infoBoxes.add(infoBox);
 		refreshInfoBoxes();
+
+		BufferedImage image = infoBox.getImage();
+
+		if (image instanceof AsyncBufferedImage)
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java]: Did you give any thought to making the spritemanager also use asyncbufferedimage? It might simplify a lot of 48f6471148c15cc9e1d63d685acbf3948ac62cb2

Comment (deathbeam) [reply runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java]: I agree, this sounds like good idea. And also would prevent the need of exposing methods from infoboxManager because then it would be handled in https://github.com/runelite/runelite/pull/9275/commits/0c32d787dc652ef6edbc95c3bf89d03113c1bffb

Comment (abextm) [reply runelite-client/src/main/java/net/runelite/client/ui/overlay/infobox/InfoBoxManager.java]: Its impossible to use AsyncBufferedImage here because I don't know the size of the image in advance, and AsyncBufferedImage cannot change size

File: runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java [hunk 2]
```diff
@@ -193,7 +193,12 @@ public void onChatMessage(ChatMessage event)
 
 			if (config.raidsTimer() && message.startsWith(RAID_START_MESSAGE))
 			{
-				timer = new RaidsTimer(spriteManager.getSprite(TAB_QUESTS_BROWN_RAIDING_PARTY, 0), this, Instant.now());
+				timer = new RaidsTimer(null, this, Instant.now());
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsPlugin.java]: This is the only reference to `RaidsTimer` so maybe remove the image from the constructor

File: runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java [hunk 3]
```diff
@@ -861,8 +860,20 @@ private TimerTimer createGameTimer(final GameTimer timer)
 	{
 		removeGameTimer(timer);
 
-		BufferedImage image = timer.getImage(itemManager, spriteManager);
-		TimerTimer t = new TimerTimer(timer, this, image);
+		TimerTimer t = new TimerTimer(timer, this, null);
```
Comment (Adam-) [inline runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java]: this, too.
